package com.allcheer.bpos.entity;

public class LeShuaLogDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LE_SHUA_LOG.REQ_SERIAL_NO
     *
     * @mbggenerated
     */
    private String reqSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LE_SHUA_LOG.BUSINESS_TYPE
     *
     * @mbggenerated
     */
    private String businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LE_SHUA_LOG.REQ_DATA
     *
     * @mbggenerated
     */
    private String reqData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LE_SHUA_LOG.SIGN
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LE_SHUA_LOG.RESP_CODE
     *
     * @mbggenerated
     */
    private String respCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LE_SHUA_LOG.RESP_MSG
     *
     * @mbggenerated
     */
    private String respMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LE_SHUA_LOG.RESP_DATA
     *
     * @mbggenerated
     */
    private String respData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LE_SHUA_LOG.UPDATE_TIME
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LE_SHUA_LOG.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LE_SHUA_LOG.REQ_SERIAL_NO
     *
     * @return the value of LE_SHUA_LOG.REQ_SERIAL_NO
     *
     * @mbggenerated
     */
    public String getReqSerialNo() {
        return reqSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LE_SHUA_LOG.REQ_SERIAL_NO
     *
     * @param reqSerialNo the value for LE_SHUA_LOG.REQ_SERIAL_NO
     *
     * @mbggenerated
     */
    public void setReqSerialNo(String reqSerialNo) {
        this.reqSerialNo = reqSerialNo == null ? null : reqSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LE_SHUA_LOG.BUSINESS_TYPE
     *
     * @return the value of LE_SHUA_LOG.BUSINESS_TYPE
     *
     * @mbggenerated
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LE_SHUA_LOG.BUSINESS_TYPE
     *
     * @param businessType the value for LE_SHUA_LOG.BUSINESS_TYPE
     *
     * @mbggenerated
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LE_SHUA_LOG.REQ_DATA
     *
     * @return the value of LE_SHUA_LOG.REQ_DATA
     *
     * @mbggenerated
     */
    public String getReqData() {
        return reqData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LE_SHUA_LOG.REQ_DATA
     *
     * @param reqData the value for LE_SHUA_LOG.REQ_DATA
     *
     * @mbggenerated
     */
    public void setReqData(String reqData) {
        this.reqData = reqData == null ? null : reqData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LE_SHUA_LOG.SIGN
     *
     * @return the value of LE_SHUA_LOG.SIGN
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LE_SHUA_LOG.SIGN
     *
     * @param sign the value for LE_SHUA_LOG.SIGN
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LE_SHUA_LOG.RESP_CODE
     *
     * @return the value of LE_SHUA_LOG.RESP_CODE
     *
     * @mbggenerated
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LE_SHUA_LOG.RESP_CODE
     *
     * @param respCode the value for LE_SHUA_LOG.RESP_CODE
     *
     * @mbggenerated
     */
    public void setRespCode(String respCode) {
        this.respCode = respCode == null ? null : respCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LE_SHUA_LOG.RESP_MSG
     *
     * @return the value of LE_SHUA_LOG.RESP_MSG
     *
     * @mbggenerated
     */
    public String getRespMsg() {
        return respMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LE_SHUA_LOG.RESP_MSG
     *
     * @param respMsg the value for LE_SHUA_LOG.RESP_MSG
     *
     * @mbggenerated
     */
    public void setRespMsg(String respMsg) {
        this.respMsg = respMsg == null ? null : respMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LE_SHUA_LOG.RESP_DATA
     *
     * @return the value of LE_SHUA_LOG.RESP_DATA
     *
     * @mbggenerated
     */
    public String getRespData() {
        return respData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LE_SHUA_LOG.RESP_DATA
     *
     * @param respData the value for LE_SHUA_LOG.RESP_DATA
     *
     * @mbggenerated
     */
    public void setRespData(String respData) {
        this.respData = respData == null ? null : respData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LE_SHUA_LOG.UPDATE_TIME
     *
     * @return the value of LE_SHUA_LOG.UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LE_SHUA_LOG.UPDATE_TIME
     *
     * @param updateTime the value for LE_SHUA_LOG.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LE_SHUA_LOG.CREATE_TIME
     *
     * @return the value of LE_SHUA_LOG.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LE_SHUA_LOG.CREATE_TIME
     *
     * @param createTime the value for LE_SHUA_LOG.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}