package com.allcheer.bpos.entity;

public class TblAgentLevelDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_LEVEL.MEMBER_ID
     *
     * @mbggenerated
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_LEVEL.UP_MEMBER_ID
     *
     * @mbggenerated
     */
    private String upMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_LEVEL.AGENT_LEVEL
     *
     * @mbggenerated
     */
    private String agentLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_LEVEL.UPDATE_TIME
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_LEVEL.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_LEVEL.MEMBER_ID
     *
     * @return the value of TBL_AGENT_LEVEL.MEMBER_ID
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_LEVEL.MEMBER_ID
     *
     * @param memberId the value for TBL_AGENT_LEVEL.MEMBER_ID
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_LEVEL.UP_MEMBER_ID
     *
     * @return the value of TBL_AGENT_LEVEL.UP_MEMBER_ID
     *
     * @mbggenerated
     */
    public String getUpMemberId() {
        return upMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_LEVEL.UP_MEMBER_ID
     *
     * @param upMemberId the value for TBL_AGENT_LEVEL.UP_MEMBER_ID
     *
     * @mbggenerated
     */
    public void setUpMemberId(String upMemberId) {
        this.upMemberId = upMemberId == null ? null : upMemberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_LEVEL.AGENT_LEVEL
     *
     * @return the value of TBL_AGENT_LEVEL.AGENT_LEVEL
     *
     * @mbggenerated
     */
    public String getAgentLevel() {
        return agentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_LEVEL.AGENT_LEVEL
     *
     * @param agentLevel the value for TBL_AGENT_LEVEL.AGENT_LEVEL
     *
     * @mbggenerated
     */
    public void setAgentLevel(String agentLevel) {
        this.agentLevel = agentLevel == null ? null : agentLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_LEVEL.UPDATE_TIME
     *
     * @return the value of TBL_AGENT_LEVEL.UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_LEVEL.UPDATE_TIME
     *
     * @param updateTime the value for TBL_AGENT_LEVEL.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_LEVEL.CREATE_TIME
     *
     * @return the value of TBL_AGENT_LEVEL.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_LEVEL.CREATE_TIME
     *
     * @param createTime the value for TBL_AGENT_LEVEL.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}