package com.allcheer.bpos.entity;

public class TblAgentMerAddBatchDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_MER_ADD_BATCH_INFO.BATCH_NO
     *
     * @mbggenerated
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_MER_ADD_BATCH_INFO.AGENT_ID
     *
     * @mbggenerated
     */
    private String agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_MER_ADD_BATCH_INFO.FILE_TYPE
     *
     * @mbggenerated
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_MER_ADD_BATCH_INFO.FILE_PATH
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_FLAG
     *
     * @mbggenerated
     */
    private String resultFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_DESC
     *
     * @mbggenerated
     */
    private String resultDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_FILE_PATH
     *
     * @mbggenerated
     */
    private String resultFilePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_MER_ADD_BATCH_INFO.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_MER_ADD_BATCH_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_AGENT_MER_ADD_BATCH_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.BATCH_NO
     *
     * @return the value of TBL_AGENT_MER_ADD_BATCH_INFO.BATCH_NO
     *
     * @mbggenerated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.BATCH_NO
     *
     * @param batchNo the value for TBL_AGENT_MER_ADD_BATCH_INFO.BATCH_NO
     *
     * @mbggenerated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.AGENT_ID
     *
     * @return the value of TBL_AGENT_MER_ADD_BATCH_INFO.AGENT_ID
     *
     * @mbggenerated
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.AGENT_ID
     *
     * @param agentId the value for TBL_AGENT_MER_ADD_BATCH_INFO.AGENT_ID
     *
     * @mbggenerated
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId == null ? null : agentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.FILE_TYPE
     *
     * @return the value of TBL_AGENT_MER_ADD_BATCH_INFO.FILE_TYPE
     *
     * @mbggenerated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.FILE_TYPE
     *
     * @param fileType the value for TBL_AGENT_MER_ADD_BATCH_INFO.FILE_TYPE
     *
     * @mbggenerated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.FILE_PATH
     *
     * @return the value of TBL_AGENT_MER_ADD_BATCH_INFO.FILE_PATH
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.FILE_PATH
     *
     * @param filePath the value for TBL_AGENT_MER_ADD_BATCH_INFO.FILE_PATH
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_FLAG
     *
     * @return the value of TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_FLAG
     *
     * @mbggenerated
     */
    public String getResultFlag() {
        return resultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_FLAG
     *
     * @param resultFlag the value for TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_FLAG
     *
     * @mbggenerated
     */
    public void setResultFlag(String resultFlag) {
        this.resultFlag = resultFlag == null ? null : resultFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_DESC
     *
     * @return the value of TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_DESC
     *
     * @mbggenerated
     */
    public String getResultDesc() {
        return resultDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_DESC
     *
     * @param resultDesc the value for TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_DESC
     *
     * @mbggenerated
     */
    public void setResultDesc(String resultDesc) {
        this.resultDesc = resultDesc == null ? null : resultDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_FILE_PATH
     *
     * @return the value of TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_FILE_PATH
     *
     * @mbggenerated
     */
    public String getResultFilePath() {
        return resultFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_FILE_PATH
     *
     * @param resultFilePath the value for TBL_AGENT_MER_ADD_BATCH_INFO.RESULT_FILE_PATH
     *
     * @mbggenerated
     */
    public void setResultFilePath(String resultFilePath) {
        this.resultFilePath = resultFilePath == null ? null : resultFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.USER_NAME
     *
     * @return the value of TBL_AGENT_MER_ADD_BATCH_INFO.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.USER_NAME
     *
     * @param userName the value for TBL_AGENT_MER_ADD_BATCH_INFO.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.UPDATE_TIME
     *
     * @return the value of TBL_AGENT_MER_ADD_BATCH_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.UPDATE_TIME
     *
     * @param updateTime the value for TBL_AGENT_MER_ADD_BATCH_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.CREATE_TIME
     *
     * @return the value of TBL_AGENT_MER_ADD_BATCH_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_AGENT_MER_ADD_BATCH_INFO.CREATE_TIME
     *
     * @param createTime the value for TBL_AGENT_MER_ADD_BATCH_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}