package com.allcheer.bpos.entity;

public class TblBTSInstStatDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_INST_STAT.INST_CODE
     *
     * @mbggenerated
     */
    private String instCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_INST_STAT.INST_HSM_INDEX
     *
     * @mbggenerated
     */
    private String instHsmIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_INST_STAT.INST_PRIM_KEY
     *
     * @mbggenerated
     */
    private String instPrimKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_INST_STAT.INST_PIN_KEY
     *
     * @mbggenerated
     */
    private String instPinKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_INST_STAT.INST_MAC_KEY
     *
     * @mbggenerated
     */
    private String instMacKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_INST_STAT.INST_TD_KEY
     *
     * @mbggenerated
     */
    private String instTdKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_INST_STAT.INST_STAT
     *
     * @mbggenerated
     */
    private String instStat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_INST_STAT.INST_CODE
     *
     * @return the value of TBL_BTS_INST_STAT.INST_CODE
     *
     * @mbggenerated
     */
    public String getInstCode() {
        return instCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_INST_STAT.INST_CODE
     *
     * @param instCode the value for TBL_BTS_INST_STAT.INST_CODE
     *
     * @mbggenerated
     */
    public void setInstCode(String instCode) {
        this.instCode = instCode == null ? null : instCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_INST_STAT.INST_HSM_INDEX
     *
     * @return the value of TBL_BTS_INST_STAT.INST_HSM_INDEX
     *
     * @mbggenerated
     */
    public String getInstHsmIndex() {
        return instHsmIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_INST_STAT.INST_HSM_INDEX
     *
     * @param instHsmIndex the value for TBL_BTS_INST_STAT.INST_HSM_INDEX
     *
     * @mbggenerated
     */
    public void setInstHsmIndex(String instHsmIndex) {
        this.instHsmIndex = instHsmIndex == null ? null : instHsmIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_INST_STAT.INST_PRIM_KEY
     *
     * @return the value of TBL_BTS_INST_STAT.INST_PRIM_KEY
     *
     * @mbggenerated
     */
    public String getInstPrimKey() {
        return instPrimKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_INST_STAT.INST_PRIM_KEY
     *
     * @param instPrimKey the value for TBL_BTS_INST_STAT.INST_PRIM_KEY
     *
     * @mbggenerated
     */
    public void setInstPrimKey(String instPrimKey) {
        this.instPrimKey = instPrimKey == null ? null : instPrimKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_INST_STAT.INST_PIN_KEY
     *
     * @return the value of TBL_BTS_INST_STAT.INST_PIN_KEY
     *
     * @mbggenerated
     */
    public String getInstPinKey() {
        return instPinKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_INST_STAT.INST_PIN_KEY
     *
     * @param instPinKey the value for TBL_BTS_INST_STAT.INST_PIN_KEY
     *
     * @mbggenerated
     */
    public void setInstPinKey(String instPinKey) {
        this.instPinKey = instPinKey == null ? null : instPinKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_INST_STAT.INST_MAC_KEY
     *
     * @return the value of TBL_BTS_INST_STAT.INST_MAC_KEY
     *
     * @mbggenerated
     */
    public String getInstMacKey() {
        return instMacKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_INST_STAT.INST_MAC_KEY
     *
     * @param instMacKey the value for TBL_BTS_INST_STAT.INST_MAC_KEY
     *
     * @mbggenerated
     */
    public void setInstMacKey(String instMacKey) {
        this.instMacKey = instMacKey == null ? null : instMacKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_INST_STAT.INST_TD_KEY
     *
     * @return the value of TBL_BTS_INST_STAT.INST_TD_KEY
     *
     * @mbggenerated
     */
    public String getInstTdKey() {
        return instTdKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_INST_STAT.INST_TD_KEY
     *
     * @param instTdKey the value for TBL_BTS_INST_STAT.INST_TD_KEY
     *
     * @mbggenerated
     */
    public void setInstTdKey(String instTdKey) {
        this.instTdKey = instTdKey == null ? null : instTdKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_INST_STAT.INST_STAT
     *
     * @return the value of TBL_BTS_INST_STAT.INST_STAT
     *
     * @mbggenerated
     */
    public String getInstStat() {
        return instStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_INST_STAT.INST_STAT
     *
     * @param instStat the value for TBL_BTS_INST_STAT.INST_STAT
     *
     * @mbggenerated
     */
    public void setInstStat(String instStat) {
        this.instStat = instStat == null ? null : instStat.trim();
    }
}