package com.allcheer.bpos.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TblBtsBMerRConfDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_BMR_CONF.BIG_MER_ID
     *
     * @mbggenerated
     */
    private String bigMerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_BMR_CONF.DAY_AMT_LIMIT
     *
     * @mbggenerated
     */
    private BigDecimal dayAmtLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_BMR_CONF.MONTH_AMT_LIMIT
     *
     * @mbggenerated
     */
    private BigDecimal monthAmtLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_BMR_CONF.CURRENT_DAY_AMT
     *
     * @mbggenerated
     */
    private BigDecimal currentDayAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_BMR_CONF.CURRENT_MOUTH_AMT
     *
     * @mbggenerated
     */
    private BigDecimal currentMouthAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_BMR_CONF.OPEN_TIME_START
     *
     * @mbggenerated
     */
    private String openTimeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_BMR_CONF.OPEN_TIME_END
     *
     * @mbggenerated
     */
    private String openTimeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_BMR_CONF.OPEN_FLAG
     *
     * @mbggenerated
     */
    private String openFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_BMR_CONF.SAFE_TIME
     *
     * @mbggenerated
     */
    private String safeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_BMR_CONF.SAFE_TIME_FLAG
     *
     * @mbggenerated
     */
    private String safeTimeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_BMR_CONF.LAST_SEND_TIME
     *
     * @mbggenerated
     */
    private Date lastSendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_BMR_CONF.BIG_MER_NAME
     *
     * @mbggenerated
     */
    private String bigMerName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_BMR_CONF.BIG_MER_ID
     *
     * @return the value of TBL_BTS_BMR_CONF.BIG_MER_ID
     *
     * @mbggenerated
     */
    public String getBigMerId() {
        return bigMerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_BMR_CONF.BIG_MER_ID
     *
     * @param bigMerId the value for TBL_BTS_BMR_CONF.BIG_MER_ID
     *
     * @mbggenerated
     */
    public void setBigMerId(String bigMerId) {
        this.bigMerId = bigMerId == null ? null : bigMerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_BMR_CONF.DAY_AMT_LIMIT
     *
     * @return the value of TBL_BTS_BMR_CONF.DAY_AMT_LIMIT
     *
     * @mbggenerated
     */
    public BigDecimal getDayAmtLimit() {
        return dayAmtLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_BMR_CONF.DAY_AMT_LIMIT
     *
     * @param dayAmtLimit the value for TBL_BTS_BMR_CONF.DAY_AMT_LIMIT
     *
     * @mbggenerated
     */
    public void setDayAmtLimit(BigDecimal dayAmtLimit) {
        this.dayAmtLimit = dayAmtLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_BMR_CONF.MONTH_AMT_LIMIT
     *
     * @return the value of TBL_BTS_BMR_CONF.MONTH_AMT_LIMIT
     *
     * @mbggenerated
     */
    public BigDecimal getMonthAmtLimit() {
        return monthAmtLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_BMR_CONF.MONTH_AMT_LIMIT
     *
     * @param monthAmtLimit the value for TBL_BTS_BMR_CONF.MONTH_AMT_LIMIT
     *
     * @mbggenerated
     */
    public void setMonthAmtLimit(BigDecimal monthAmtLimit) {
        this.monthAmtLimit = monthAmtLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_BMR_CONF.CURRENT_DAY_AMT
     *
     * @return the value of TBL_BTS_BMR_CONF.CURRENT_DAY_AMT
     *
     * @mbggenerated
     */
    public BigDecimal getCurrentDayAmt() {
        return currentDayAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_BMR_CONF.CURRENT_DAY_AMT
     *
     * @param currentDayAmt the value for TBL_BTS_BMR_CONF.CURRENT_DAY_AMT
     *
     * @mbggenerated
     */
    public void setCurrentDayAmt(BigDecimal currentDayAmt) {
        this.currentDayAmt = currentDayAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_BMR_CONF.CURRENT_MOUTH_AMT
     *
     * @return the value of TBL_BTS_BMR_CONF.CURRENT_MOUTH_AMT
     *
     * @mbggenerated
     */
    public BigDecimal getCurrentMouthAmt() {
        return currentMouthAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_BMR_CONF.CURRENT_MOUTH_AMT
     *
     * @param currentMouthAmt the value for TBL_BTS_BMR_CONF.CURRENT_MOUTH_AMT
     *
     * @mbggenerated
     */
    public void setCurrentMouthAmt(BigDecimal currentMouthAmt) {
        this.currentMouthAmt = currentMouthAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_BMR_CONF.OPEN_TIME_START
     *
     * @return the value of TBL_BTS_BMR_CONF.OPEN_TIME_START
     *
     * @mbggenerated
     */
    public String getOpenTimeStart() {
        return openTimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_BMR_CONF.OPEN_TIME_START
     *
     * @param openTimeStart the value for TBL_BTS_BMR_CONF.OPEN_TIME_START
     *
     * @mbggenerated
     */
    public void setOpenTimeStart(String openTimeStart) {
        this.openTimeStart = openTimeStart == null ? null : openTimeStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_BMR_CONF.OPEN_TIME_END
     *
     * @return the value of TBL_BTS_BMR_CONF.OPEN_TIME_END
     *
     * @mbggenerated
     */
    public String getOpenTimeEnd() {
        return openTimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_BMR_CONF.OPEN_TIME_END
     *
     * @param openTimeEnd the value for TBL_BTS_BMR_CONF.OPEN_TIME_END
     *
     * @mbggenerated
     */
    public void setOpenTimeEnd(String openTimeEnd) {
        this.openTimeEnd = openTimeEnd == null ? null : openTimeEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_BMR_CONF.OPEN_FLAG
     *
     * @return the value of TBL_BTS_BMR_CONF.OPEN_FLAG
     *
     * @mbggenerated
     */
    public String getOpenFlag() {
        return openFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_BMR_CONF.OPEN_FLAG
     *
     * @param openFlag the value for TBL_BTS_BMR_CONF.OPEN_FLAG
     *
     * @mbggenerated
     */
    public void setOpenFlag(String openFlag) {
        this.openFlag = openFlag == null ? null : openFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_BMR_CONF.SAFE_TIME
     *
     * @return the value of TBL_BTS_BMR_CONF.SAFE_TIME
     *
     * @mbggenerated
     */
    public String getSafeTime() {
        return safeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_BMR_CONF.SAFE_TIME
     *
     * @param safeTime the value for TBL_BTS_BMR_CONF.SAFE_TIME
     *
     * @mbggenerated
     */
    public void setSafeTime(String safeTime) {
        this.safeTime = safeTime == null ? null : safeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_BMR_CONF.SAFE_TIME_FLAG
     *
     * @return the value of TBL_BTS_BMR_CONF.SAFE_TIME_FLAG
     *
     * @mbggenerated
     */
    public String getSafeTimeFlag() {
        return safeTimeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_BMR_CONF.SAFE_TIME_FLAG
     *
     * @param safeTimeFlag the value for TBL_BTS_BMR_CONF.SAFE_TIME_FLAG
     *
     * @mbggenerated
     */
    public void setSafeTimeFlag(String safeTimeFlag) {
        this.safeTimeFlag = safeTimeFlag == null ? null : safeTimeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_BMR_CONF.LAST_SEND_TIME
     *
     * @return the value of TBL_BTS_BMR_CONF.LAST_SEND_TIME
     *
     * @mbggenerated
     */
    public Date getLastSendTime() {
        return lastSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_BMR_CONF.LAST_SEND_TIME
     *
     * @param lastSendTime the value for TBL_BTS_BMR_CONF.LAST_SEND_TIME
     *
     * @mbggenerated
     */
    public void setLastSendTime(Date lastSendTime) {
        this.lastSendTime = lastSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_BMR_CONF.BIG_MER_NAME
     *
     * @return the value of TBL_BTS_BMR_CONF.BIG_MER_NAME
     *
     * @mbggenerated
     */
    public String getBigMerName() {
        return bigMerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_BMR_CONF.BIG_MER_NAME
     *
     * @param bigMerName the value for TBL_BTS_BMR_CONF.BIG_MER_NAME
     *
     * @mbggenerated
     */
    public void setBigMerName(String bigMerName) {
        this.bigMerName = bigMerName == null ? null : bigMerName.trim();
    }
}