package com.allcheer.bpos.entity;

public class TblBankWxInfoDOKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BANK_WECHAT_INFO.GATE_ID
     *
     * @mbggenerated
     */
    private String gateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BANK_WECHAT_INFO.MER_ID
     *
     * @mbggenerated
     */
    private String merId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BANK_WECHAT_INFO.GATE_ID
     *
     * @return the value of TBL_BANK_WECHAT_INFO.GATE_ID
     *
     * @mbggenerated
     */
    public String getGateId() {
        return gateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BANK_WECHAT_INFO.GATE_ID
     *
     * @param gateId the value for TBL_BANK_WECHAT_INFO.GATE_ID
     *
     * @mbggenerated
     */
    public void setGateId(String gateId) {
        this.gateId = gateId == null ? null : gateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BANK_WECHAT_INFO.MER_ID
     *
     * @return the value of TBL_BANK_WECHAT_INFO.MER_ID
     *
     * @mbggenerated
     */
    public String getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BANK_WECHAT_INFO.MER_ID
     *
     * @param merId the value for TBL_BANK_WECHAT_INFO.MER_ID
     *
     * @mbggenerated
     */
    public void setMerId(String merId) {
        this.merId = merId == null ? null : merId.trim();
    }
}