package com.allcheer.bpos.entity;

public class TblChannelCheckFileInfoDO extends TblChannelCheckFileInfoDOKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_CHANNEL_CHECK_FILE_INFO.FILE_NO
     *
     * @mbggenerated
     */
    private String fileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_CHANNEL_CHECK_FILE_INFO.CHECK_STAT
     *
     * @mbggenerated
     */
    private String checkStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_CHANNEL_CHECK_FILE_INFO.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_CHANNEL_CHECK_FILE_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_CHANNEL_CHECK_FILE_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_CHANNEL_CHECK_FILE_INFO.FILE_NO
     *
     * @return the value of TBL_CHANNEL_CHECK_FILE_INFO.FILE_NO
     *
     * @mbggenerated
     */
    public String getFileNo() {
        return fileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_CHANNEL_CHECK_FILE_INFO.FILE_NO
     *
     * @param fileNo the value for TBL_CHANNEL_CHECK_FILE_INFO.FILE_NO
     *
     * @mbggenerated
     */
    public void setFileNo(String fileNo) {
        this.fileNo = fileNo == null ? null : fileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_CHANNEL_CHECK_FILE_INFO.CHECK_STAT
     *
     * @return the value of TBL_CHANNEL_CHECK_FILE_INFO.CHECK_STAT
     *
     * @mbggenerated
     */
    public String getCheckStat() {
        return checkStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_CHANNEL_CHECK_FILE_INFO.CHECK_STAT
     *
     * @param checkStat the value for TBL_CHANNEL_CHECK_FILE_INFO.CHECK_STAT
     *
     * @mbggenerated
     */
    public void setCheckStat(String checkStat) {
        this.checkStat = checkStat == null ? null : checkStat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_CHANNEL_CHECK_FILE_INFO.USER_NAME
     *
     * @return the value of TBL_CHANNEL_CHECK_FILE_INFO.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_CHANNEL_CHECK_FILE_INFO.USER_NAME
     *
     * @param userName the value for TBL_CHANNEL_CHECK_FILE_INFO.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_CHANNEL_CHECK_FILE_INFO.UPDATE_TIME
     *
     * @return the value of TBL_CHANNEL_CHECK_FILE_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_CHANNEL_CHECK_FILE_INFO.UPDATE_TIME
     *
     * @param updateTime the value for TBL_CHANNEL_CHECK_FILE_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_CHANNEL_CHECK_FILE_INFO.CREATE_TIME
     *
     * @return the value of TBL_CHANNEL_CHECK_FILE_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_CHANNEL_CHECK_FILE_INFO.CREATE_TIME
     *
     * @param createTime the value for TBL_CHANNEL_CHECK_FILE_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}