package com.allcheer.bpos.entity;

public class TblInstRouteControl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_ROUTE_CONTROL.ROUTE_SEQ
     *
     * @mbggenerated
     */
    private String routeSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_ROUTE_CONTROL.INST_CODE
     *
     * @mbggenerated
     */
    private String instCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_ROUTE_CONTROL.INST_MER_ID
     *
     * @mbggenerated
     */
    private String instMerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_ROUTE_CONTROL.INST_MER_TERM_ID
     *
     * @mbggenerated
     */
    private String instMerTermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_ROUTE_CONTROL.GATE_ID
     *
     * @mbggenerated
     */
    private String gateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_ROUTE_CONTROL.INST_BANK_MER_ID
     *
     * @mbggenerated
     */
    private String instBankMerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_ROUTE_CONTROL.BANK_MER_ID
     *
     * @mbggenerated
     */
    private String bankMerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_ROUTE_CONTROL.STAT
     *
     * @mbggenerated
     */
    private String stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_ROUTE_CONTROL.ROUTE_SEQ
     *
     * @return the value of TBL_INST_ROUTE_CONTROL.ROUTE_SEQ
     *
     * @mbggenerated
     */
    public String getRouteSeq() {
        return routeSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_ROUTE_CONTROL.ROUTE_SEQ
     *
     * @param routeSeq the value for TBL_INST_ROUTE_CONTROL.ROUTE_SEQ
     *
     * @mbggenerated
     */
    public void setRouteSeq(String routeSeq) {
        this.routeSeq = routeSeq == null ? null : routeSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_ROUTE_CONTROL.INST_CODE
     *
     * @return the value of TBL_INST_ROUTE_CONTROL.INST_CODE
     *
     * @mbggenerated
     */
    public String getInstCode() {
        return instCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_ROUTE_CONTROL.INST_CODE
     *
     * @param instCode the value for TBL_INST_ROUTE_CONTROL.INST_CODE
     *
     * @mbggenerated
     */
    public void setInstCode(String instCode) {
        this.instCode = instCode == null ? null : instCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_ROUTE_CONTROL.INST_MER_ID
     *
     * @return the value of TBL_INST_ROUTE_CONTROL.INST_MER_ID
     *
     * @mbggenerated
     */
    public String getInstMerId() {
        return instMerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_ROUTE_CONTROL.INST_MER_ID
     *
     * @param instMerId the value for TBL_INST_ROUTE_CONTROL.INST_MER_ID
     *
     * @mbggenerated
     */
    public void setInstMerId(String instMerId) {
        this.instMerId = instMerId == null ? null : instMerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_ROUTE_CONTROL.INST_MER_TERM_ID
     *
     * @return the value of TBL_INST_ROUTE_CONTROL.INST_MER_TERM_ID
     *
     * @mbggenerated
     */
    public String getInstMerTermId() {
        return instMerTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_ROUTE_CONTROL.INST_MER_TERM_ID
     *
     * @param instMerTermId the value for TBL_INST_ROUTE_CONTROL.INST_MER_TERM_ID
     *
     * @mbggenerated
     */
    public void setInstMerTermId(String instMerTermId) {
        this.instMerTermId = instMerTermId == null ? null : instMerTermId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_ROUTE_CONTROL.GATE_ID
     *
     * @return the value of TBL_INST_ROUTE_CONTROL.GATE_ID
     *
     * @mbggenerated
     */
    public String getGateId() {
        return gateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_ROUTE_CONTROL.GATE_ID
     *
     * @param gateId the value for TBL_INST_ROUTE_CONTROL.GATE_ID
     *
     * @mbggenerated
     */
    public void setGateId(String gateId) {
        this.gateId = gateId == null ? null : gateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_ROUTE_CONTROL.INST_BANK_MER_ID
     *
     * @return the value of TBL_INST_ROUTE_CONTROL.INST_BANK_MER_ID
     *
     * @mbggenerated
     */
    public String getInstBankMerId() {
        return instBankMerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_ROUTE_CONTROL.INST_BANK_MER_ID
     *
     * @param instBankMerId the value for TBL_INST_ROUTE_CONTROL.INST_BANK_MER_ID
     *
     * @mbggenerated
     */
    public void setInstBankMerId(String instBankMerId) {
        this.instBankMerId = instBankMerId == null ? null : instBankMerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_ROUTE_CONTROL.BANK_MER_ID
     *
     * @return the value of TBL_INST_ROUTE_CONTROL.BANK_MER_ID
     *
     * @mbggenerated
     */
    public String getBankMerId() {
        return bankMerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_ROUTE_CONTROL.BANK_MER_ID
     *
     * @param bankMerId the value for TBL_INST_ROUTE_CONTROL.BANK_MER_ID
     *
     * @mbggenerated
     */
    public void setBankMerId(String bankMerId) {
        this.bankMerId = bankMerId == null ? null : bankMerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_ROUTE_CONTROL.STAT
     *
     * @return the value of TBL_INST_ROUTE_CONTROL.STAT
     *
     * @mbggenerated
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_ROUTE_CONTROL.STAT
     *
     * @param stat the value for TBL_INST_ROUTE_CONTROL.STAT
     *
     * @mbggenerated
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }
}