package com.allcheer.bpos.entity;

public class TblInstChannelMapDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_CHANNEL_MAP.INST_ID
     *
     * @mbggenerated
     */
    private String instId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_CHANNEL_MAP.INST_MER_ID
     *
     * @mbggenerated
     */
    private String instMerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_CHANNEL_MAP.INST_MER_TERM_ID
     *
     * @mbggenerated
     */
    private String instMerTermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_CHANNEL_MAP.CHANNEL_ID
     *
     * @mbggenerated
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_CHANNEL_MAP.CHANNEL_MER_ID
     *
     * @mbggenerated
     */
    private String channelMerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_CHANNEL_MAP.CHANNEL_MER_TERM_ID
     *
     * @mbggenerated
     */
    private String channelMerTermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_CHANNEL_MAP.STATUS_FLAG
     *
     * @mbggenerated
     */
    private String statusFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_CHANNEL_MAP.RESV
     *
     * @mbggenerated
     */
    private String resv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_CHANNEL_MAP.INST_ID
     *
     * @return the value of TBL_INST_CHANNEL_MAP.INST_ID
     *
     * @mbggenerated
     */
    public String getInstId() {
        return instId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_CHANNEL_MAP.INST_ID
     *
     * @param instId the value for TBL_INST_CHANNEL_MAP.INST_ID
     *
     * @mbggenerated
     */
    public void setInstId(String instId) {
        this.instId = instId == null ? null : instId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_CHANNEL_MAP.INST_MER_ID
     *
     * @return the value of TBL_INST_CHANNEL_MAP.INST_MER_ID
     *
     * @mbggenerated
     */
    public String getInstMerId() {
        return instMerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_CHANNEL_MAP.INST_MER_ID
     *
     * @param instMerId the value for TBL_INST_CHANNEL_MAP.INST_MER_ID
     *
     * @mbggenerated
     */
    public void setInstMerId(String instMerId) {
        this.instMerId = instMerId == null ? null : instMerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_CHANNEL_MAP.INST_MER_TERM_ID
     *
     * @return the value of TBL_INST_CHANNEL_MAP.INST_MER_TERM_ID
     *
     * @mbggenerated
     */
    public String getInstMerTermId() {
        return instMerTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_CHANNEL_MAP.INST_MER_TERM_ID
     *
     * @param instMerTermId the value for TBL_INST_CHANNEL_MAP.INST_MER_TERM_ID
     *
     * @mbggenerated
     */
    public void setInstMerTermId(String instMerTermId) {
        this.instMerTermId = instMerTermId == null ? null : instMerTermId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_CHANNEL_MAP.CHANNEL_ID
     *
     * @return the value of TBL_INST_CHANNEL_MAP.CHANNEL_ID
     *
     * @mbggenerated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_CHANNEL_MAP.CHANNEL_ID
     *
     * @param channelId the value for TBL_INST_CHANNEL_MAP.CHANNEL_ID
     *
     * @mbggenerated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_CHANNEL_MAP.CHANNEL_MER_ID
     *
     * @return the value of TBL_INST_CHANNEL_MAP.CHANNEL_MER_ID
     *
     * @mbggenerated
     */
    public String getChannelMerId() {
        return channelMerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_CHANNEL_MAP.CHANNEL_MER_ID
     *
     * @param channelMerId the value for TBL_INST_CHANNEL_MAP.CHANNEL_MER_ID
     *
     * @mbggenerated
     */
    public void setChannelMerId(String channelMerId) {
        this.channelMerId = channelMerId == null ? null : channelMerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_CHANNEL_MAP.CHANNEL_MER_TERM_ID
     *
     * @return the value of TBL_INST_CHANNEL_MAP.CHANNEL_MER_TERM_ID
     *
     * @mbggenerated
     */
    public String getChannelMerTermId() {
        return channelMerTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_CHANNEL_MAP.CHANNEL_MER_TERM_ID
     *
     * @param channelMerTermId the value for TBL_INST_CHANNEL_MAP.CHANNEL_MER_TERM_ID
     *
     * @mbggenerated
     */
    public void setChannelMerTermId(String channelMerTermId) {
        this.channelMerTermId = channelMerTermId == null ? null : channelMerTermId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_CHANNEL_MAP.STATUS_FLAG
     *
     * @return the value of TBL_INST_CHANNEL_MAP.STATUS_FLAG
     *
     * @mbggenerated
     */
    public String getStatusFlag() {
        return statusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_CHANNEL_MAP.STATUS_FLAG
     *
     * @param statusFlag the value for TBL_INST_CHANNEL_MAP.STATUS_FLAG
     *
     * @mbggenerated
     */
    public void setStatusFlag(String statusFlag) {
        this.statusFlag = statusFlag == null ? null : statusFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_CHANNEL_MAP.RESV
     *
     * @return the value of TBL_INST_CHANNEL_MAP.RESV
     *
     * @mbggenerated
     */
    public String getResv() {
        return resv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_CHANNEL_MAP.RESV
     *
     * @param resv the value for TBL_INST_CHANNEL_MAP.RESV
     *
     * @mbggenerated
     */
    public void setResv(String resv) {
        this.resv = resv == null ? null : resv.trim();
    }
}