package com.allcheer.bpos.entity;

public class TblInstMerTermRelDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_MER_TERM_REL.MER_ID
     *
     * @mbggenerated
     */
    private String merId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_MER_TERM_REL.TERM_ID
     *
     * @mbggenerated
     */
    private String termId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_MER_TERM_REL.INST_ID
     *
     * @mbggenerated
     */
    private String instId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_MER_TERM_REL.INST_MER_ID
     *
     * @mbggenerated
     */
    private String instMerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_MER_TERM_REL.INST_TERM_ID
     *
     * @mbggenerated
     */
    private String instTermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_MER_TERM_REL.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_MER_TERM_REL.UPDATE_TIME
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_INST_MER_TERM_REL.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_MER_TERM_REL.MER_ID
     *
     * @return the value of TBL_INST_MER_TERM_REL.MER_ID
     *
     * @mbggenerated
     */
    public String getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_MER_TERM_REL.MER_ID
     *
     * @param merId the value for TBL_INST_MER_TERM_REL.MER_ID
     *
     * @mbggenerated
     */
    public void setMerId(String merId) {
        this.merId = merId == null ? null : merId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_MER_TERM_REL.TERM_ID
     *
     * @return the value of TBL_INST_MER_TERM_REL.TERM_ID
     *
     * @mbggenerated
     */
    public String getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_MER_TERM_REL.TERM_ID
     *
     * @param termId the value for TBL_INST_MER_TERM_REL.TERM_ID
     *
     * @mbggenerated
     */
    public void setTermId(String termId) {
        this.termId = termId == null ? null : termId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_MER_TERM_REL.INST_ID
     *
     * @return the value of TBL_INST_MER_TERM_REL.INST_ID
     *
     * @mbggenerated
     */
    public String getInstId() {
        return instId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_MER_TERM_REL.INST_ID
     *
     * @param instId the value for TBL_INST_MER_TERM_REL.INST_ID
     *
     * @mbggenerated
     */
    public void setInstId(String instId) {
        this.instId = instId == null ? null : instId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_MER_TERM_REL.INST_MER_ID
     *
     * @return the value of TBL_INST_MER_TERM_REL.INST_MER_ID
     *
     * @mbggenerated
     */
    public String getInstMerId() {
        return instMerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_MER_TERM_REL.INST_MER_ID
     *
     * @param instMerId the value for TBL_INST_MER_TERM_REL.INST_MER_ID
     *
     * @mbggenerated
     */
    public void setInstMerId(String instMerId) {
        this.instMerId = instMerId == null ? null : instMerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_MER_TERM_REL.INST_TERM_ID
     *
     * @return the value of TBL_INST_MER_TERM_REL.INST_TERM_ID
     *
     * @mbggenerated
     */
    public String getInstTermId() {
        return instTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_MER_TERM_REL.INST_TERM_ID
     *
     * @param instTermId the value for TBL_INST_MER_TERM_REL.INST_TERM_ID
     *
     * @mbggenerated
     */
    public void setInstTermId(String instTermId) {
        this.instTermId = instTermId == null ? null : instTermId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_MER_TERM_REL.USER_NAME
     *
     * @return the value of TBL_INST_MER_TERM_REL.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_MER_TERM_REL.USER_NAME
     *
     * @param userName the value for TBL_INST_MER_TERM_REL.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_MER_TERM_REL.UPDATE_TIME
     *
     * @return the value of TBL_INST_MER_TERM_REL.UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_MER_TERM_REL.UPDATE_TIME
     *
     * @param updateTime the value for TBL_INST_MER_TERM_REL.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_INST_MER_TERM_REL.CREATE_TIME
     *
     * @return the value of TBL_INST_MER_TERM_REL.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_INST_MER_TERM_REL.CREATE_TIME
     *
     * @param createTime the value for TBL_INST_MER_TERM_REL.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}