package com.allcheer.bpos.entity;

import java.util.ArrayList;
import java.util.List;

public class TblMerRelevanceMccDoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    public TblMerRelevanceMccDoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMccIdIsNull() {
            addCriterion("MCC_ID is null");
            return (Criteria) this;
        }

        public Criteria andMccIdIsNotNull() {
            addCriterion("MCC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMccIdEqualTo(String value) {
            addCriterion("MCC_ID =", value, "mccId");
            return (Criteria) this;
        }

        public Criteria andMccIdNotEqualTo(String value) {
            addCriterion("MCC_ID <>", value, "mccId");
            return (Criteria) this;
        }

        public Criteria andMccIdGreaterThan(String value) {
            addCriterion("MCC_ID >", value, "mccId");
            return (Criteria) this;
        }

        public Criteria andMccIdGreaterThanOrEqualTo(String value) {
            addCriterion("MCC_ID >=", value, "mccId");
            return (Criteria) this;
        }

        public Criteria andMccIdLessThan(String value) {
            addCriterion("MCC_ID <", value, "mccId");
            return (Criteria) this;
        }

        public Criteria andMccIdLessThanOrEqualTo(String value) {
            addCriterion("MCC_ID <=", value, "mccId");
            return (Criteria) this;
        }

        public Criteria andMccIdLike(String value) {
            addCriterion("MCC_ID like", value, "mccId");
            return (Criteria) this;
        }

        public Criteria andMccIdNotLike(String value) {
            addCriterion("MCC_ID not like", value, "mccId");
            return (Criteria) this;
        }

        public Criteria andMccIdIn(List<String> values) {
            addCriterion("MCC_ID in", values, "mccId");
            return (Criteria) this;
        }

        public Criteria andMccIdNotIn(List<String> values) {
            addCriterion("MCC_ID not in", values, "mccId");
            return (Criteria) this;
        }

        public Criteria andMccIdBetween(String value1, String value2) {
            addCriterion("MCC_ID between", value1, value2, "mccId");
            return (Criteria) this;
        }

        public Criteria andMccIdNotBetween(String value1, String value2) {
            addCriterion("MCC_ID not between", value1, value2, "mccId");
            return (Criteria) this;
        }

        public Criteria andMccValueIsNull() {
            addCriterion("MCC_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andMccValueIsNotNull() {
            addCriterion("MCC_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andMccValueEqualTo(String value) {
            addCriterion("MCC_VALUE =", value, "mccValue");
            return (Criteria) this;
        }

        public Criteria andMccValueNotEqualTo(String value) {
            addCriterion("MCC_VALUE <>", value, "mccValue");
            return (Criteria) this;
        }

        public Criteria andMccValueGreaterThan(String value) {
            addCriterion("MCC_VALUE >", value, "mccValue");
            return (Criteria) this;
        }

        public Criteria andMccValueGreaterThanOrEqualTo(String value) {
            addCriterion("MCC_VALUE >=", value, "mccValue");
            return (Criteria) this;
        }

        public Criteria andMccValueLessThan(String value) {
            addCriterion("MCC_VALUE <", value, "mccValue");
            return (Criteria) this;
        }

        public Criteria andMccValueLessThanOrEqualTo(String value) {
            addCriterion("MCC_VALUE <=", value, "mccValue");
            return (Criteria) this;
        }

        public Criteria andMccValueLike(String value) {
            addCriterion("MCC_VALUE like", value, "mccValue");
            return (Criteria) this;
        }

        public Criteria andMccValueNotLike(String value) {
            addCriterion("MCC_VALUE not like", value, "mccValue");
            return (Criteria) this;
        }

        public Criteria andMccValueIn(List<String> values) {
            addCriterion("MCC_VALUE in", values, "mccValue");
            return (Criteria) this;
        }

        public Criteria andMccValueNotIn(List<String> values) {
            addCriterion("MCC_VALUE not in", values, "mccValue");
            return (Criteria) this;
        }

        public Criteria andMccValueBetween(String value1, String value2) {
            addCriterion("MCC_VALUE between", value1, value2, "mccValue");
            return (Criteria) this;
        }

        public Criteria andMccValueNotBetween(String value1, String value2) {
            addCriterion("MCC_VALUE not between", value1, value2, "mccValue");
            return (Criteria) this;
        }

        public Criteria andMccDespIsNull() {
            addCriterion("MCC_DESP is null");
            return (Criteria) this;
        }

        public Criteria andMccDespIsNotNull() {
            addCriterion("MCC_DESP is not null");
            return (Criteria) this;
        }

        public Criteria andMccDespEqualTo(String value) {
            addCriterion("MCC_DESP =", value, "mccDesp");
            return (Criteria) this;
        }

        public Criteria andMccDespNotEqualTo(String value) {
            addCriterion("MCC_DESP <>", value, "mccDesp");
            return (Criteria) this;
        }

        public Criteria andMccDespGreaterThan(String value) {
            addCriterion("MCC_DESP >", value, "mccDesp");
            return (Criteria) this;
        }

        public Criteria andMccDespGreaterThanOrEqualTo(String value) {
            addCriterion("MCC_DESP >=", value, "mccDesp");
            return (Criteria) this;
        }

        public Criteria andMccDespLessThan(String value) {
            addCriterion("MCC_DESP <", value, "mccDesp");
            return (Criteria) this;
        }

        public Criteria andMccDespLessThanOrEqualTo(String value) {
            addCriterion("MCC_DESP <=", value, "mccDesp");
            return (Criteria) this;
        }

        public Criteria andMccDespLike(String value) {
            addCriterion("MCC_DESP like", value, "mccDesp");
            return (Criteria) this;
        }

        public Criteria andMccDespNotLike(String value) {
            addCriterion("MCC_DESP not like", value, "mccDesp");
            return (Criteria) this;
        }

        public Criteria andMccDespIn(List<String> values) {
            addCriterion("MCC_DESP in", values, "mccDesp");
            return (Criteria) this;
        }

        public Criteria andMccDespNotIn(List<String> values) {
            addCriterion("MCC_DESP not in", values, "mccDesp");
            return (Criteria) this;
        }

        public Criteria andMccDespBetween(String value1, String value2) {
            addCriterion("MCC_DESP between", value1, value2, "mccDesp");
            return (Criteria) this;
        }

        public Criteria andMccDespNotBetween(String value1, String value2) {
            addCriterion("MCC_DESP not between", value1, value2, "mccDesp");
            return (Criteria) this;
        }

        public Criteria andMerIdIsNull() {
            addCriterion("MER_ID is null");
            return (Criteria) this;
        }

        public Criteria andMerIdIsNotNull() {
            addCriterion("MER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMerIdEqualTo(String value) {
            addCriterion("MER_ID =", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotEqualTo(String value) {
            addCriterion("MER_ID <>", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdGreaterThan(String value) {
            addCriterion("MER_ID >", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdGreaterThanOrEqualTo(String value) {
            addCriterion("MER_ID >=", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdLessThan(String value) {
            addCriterion("MER_ID <", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdLessThanOrEqualTo(String value) {
            addCriterion("MER_ID <=", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdLike(String value) {
            addCriterion("MER_ID like", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotLike(String value) {
            addCriterion("MER_ID not like", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdIn(List<String> values) {
            addCriterion("MER_ID in", values, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotIn(List<String> values) {
            addCriterion("MER_ID not in", values, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdBetween(String value1, String value2) {
            addCriterion("MER_ID between", value1, value2, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotBetween(String value1, String value2) {
            addCriterion("MER_ID not between", value1, value2, "merId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("UPDATE_TIME like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("UPDATE_TIME not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}