package com.allcheer.bpos.entity;

import java.util.ArrayList;
import java.util.List;

public class TblMerFileInfoDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    public TblMerFileInfoDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInstIdIsNull() {
            addCriterion("INST_ID is null");
            return (Criteria) this;
        }

        public Criteria andInstIdIsNotNull() {
            addCriterion("INST_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInstIdEqualTo(String value) {
            addCriterion("INST_ID =", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdNotEqualTo(String value) {
            addCriterion("INST_ID <>", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdGreaterThan(String value) {
            addCriterion("INST_ID >", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdGreaterThanOrEqualTo(String value) {
            addCriterion("INST_ID >=", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdLessThan(String value) {
            addCriterion("INST_ID <", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdLessThanOrEqualTo(String value) {
            addCriterion("INST_ID <=", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdLike(String value) {
            addCriterion("INST_ID like", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdNotLike(String value) {
            addCriterion("INST_ID not like", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdIn(List<String> values) {
            addCriterion("INST_ID in", values, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdNotIn(List<String> values) {
            addCriterion("INST_ID not in", values, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdBetween(String value1, String value2) {
            addCriterion("INST_ID between", value1, value2, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdNotBetween(String value1, String value2) {
            addCriterion("INST_ID not between", value1, value2, "instId");
            return (Criteria) this;
        }

        public Criteria andMerIdIsNull() {
            addCriterion("MER_ID is null");
            return (Criteria) this;
        }

        public Criteria andMerIdIsNotNull() {
            addCriterion("MER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMerIdEqualTo(String value) {
            addCriterion("MER_ID =", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotEqualTo(String value) {
            addCriterion("MER_ID <>", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdGreaterThan(String value) {
            addCriterion("MER_ID >", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdGreaterThanOrEqualTo(String value) {
            addCriterion("MER_ID >=", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdLessThan(String value) {
            addCriterion("MER_ID <", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdLessThanOrEqualTo(String value) {
            addCriterion("MER_ID <=", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdLike(String value) {
            addCriterion("MER_ID like", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotLike(String value) {
            addCriterion("MER_ID not like", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdIn(List<String> values) {
            addCriterion("MER_ID in", values, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotIn(List<String> values) {
            addCriterion("MER_ID not in", values, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdBetween(String value1, String value2) {
            addCriterion("MER_ID between", value1, value2, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotBetween(String value1, String value2) {
            addCriterion("MER_ID not between", value1, value2, "merId");
            return (Criteria) this;
        }

        public Criteria andInstMerIdIsNull() {
            addCriterion("INST_MER_ID is null");
            return (Criteria) this;
        }

        public Criteria andInstMerIdIsNotNull() {
            addCriterion("INST_MER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInstMerIdEqualTo(String value) {
            addCriterion("INST_MER_ID =", value, "instMerId");
            return (Criteria) this;
        }

        public Criteria andInstMerIdNotEqualTo(String value) {
            addCriterion("INST_MER_ID <>", value, "instMerId");
            return (Criteria) this;
        }

        public Criteria andInstMerIdGreaterThan(String value) {
            addCriterion("INST_MER_ID >", value, "instMerId");
            return (Criteria) this;
        }

        public Criteria andInstMerIdGreaterThanOrEqualTo(String value) {
            addCriterion("INST_MER_ID >=", value, "instMerId");
            return (Criteria) this;
        }

        public Criteria andInstMerIdLessThan(String value) {
            addCriterion("INST_MER_ID <", value, "instMerId");
            return (Criteria) this;
        }

        public Criteria andInstMerIdLessThanOrEqualTo(String value) {
            addCriterion("INST_MER_ID <=", value, "instMerId");
            return (Criteria) this;
        }

        public Criteria andInstMerIdLike(String value) {
            addCriterion("INST_MER_ID like", value, "instMerId");
            return (Criteria) this;
        }

        public Criteria andInstMerIdNotLike(String value) {
            addCriterion("INST_MER_ID not like", value, "instMerId");
            return (Criteria) this;
        }

        public Criteria andInstMerIdIn(List<String> values) {
            addCriterion("INST_MER_ID in", values, "instMerId");
            return (Criteria) this;
        }

        public Criteria andInstMerIdNotIn(List<String> values) {
            addCriterion("INST_MER_ID not in", values, "instMerId");
            return (Criteria) this;
        }

        public Criteria andInstMerIdBetween(String value1, String value2) {
            addCriterion("INST_MER_ID between", value1, value2, "instMerId");
            return (Criteria) this;
        }

        public Criteria andInstMerIdNotBetween(String value1, String value2) {
            addCriterion("INST_MER_ID not between", value1, value2, "instMerId");
            return (Criteria) this;
        }

        public Criteria andPicAddress1IsNull() {
            addCriterion("PIC_ADDRESS1 is null");
            return (Criteria) this;
        }

        public Criteria andPicAddress1IsNotNull() {
            addCriterion("PIC_ADDRESS1 is not null");
            return (Criteria) this;
        }

        public Criteria andPicAddress1EqualTo(String value) {
            addCriterion("PIC_ADDRESS1 =", value, "picAddress1");
            return (Criteria) this;
        }

        public Criteria andPicAddress1NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS1 <>", value, "picAddress1");
            return (Criteria) this;
        }

        public Criteria andPicAddress1GreaterThan(String value) {
            addCriterion("PIC_ADDRESS1 >", value, "picAddress1");
            return (Criteria) this;
        }

        public Criteria andPicAddress1GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS1 >=", value, "picAddress1");
            return (Criteria) this;
        }

        public Criteria andPicAddress1LessThan(String value) {
            addCriterion("PIC_ADDRESS1 <", value, "picAddress1");
            return (Criteria) this;
        }

        public Criteria andPicAddress1LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS1 <=", value, "picAddress1");
            return (Criteria) this;
        }

        public Criteria andPicAddress1Like(String value) {
            addCriterion("PIC_ADDRESS1 like", value, "picAddress1");
            return (Criteria) this;
        }

        public Criteria andPicAddress1NotLike(String value) {
            addCriterion("PIC_ADDRESS1 not like", value, "picAddress1");
            return (Criteria) this;
        }

        public Criteria andPicAddress1In(List<String> values) {
            addCriterion("PIC_ADDRESS1 in", values, "picAddress1");
            return (Criteria) this;
        }

        public Criteria andPicAddress1NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS1 not in", values, "picAddress1");
            return (Criteria) this;
        }

        public Criteria andPicAddress1Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS1 between", value1, value2, "picAddress1");
            return (Criteria) this;
        }

        public Criteria andPicAddress1NotBetween(String value1, String value2) {
            addCriterion("PIC_ADDRESS1 not between", value1, value2, "picAddress1");
            return (Criteria) this;
        }

        public Criteria andPicAddress2IsNull() {
            addCriterion("PIC_ADDRESS2 is null");
            return (Criteria) this;
        }

        public Criteria andPicAddress2IsNotNull() {
            addCriterion("PIC_ADDRESS2 is not null");
            return (Criteria) this;
        }

        public Criteria andPicAddress2EqualTo(String value) {
            addCriterion("PIC_ADDRESS2 =", value, "picAddress2");
            return (Criteria) this;
        }

        public Criteria andPicAddress2NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS2 <>", value, "picAddress2");
            return (Criteria) this;
        }

        public Criteria andPicAddress2GreaterThan(String value) {
            addCriterion("PIC_ADDRESS2 >", value, "picAddress2");
            return (Criteria) this;
        }

        public Criteria andPicAddress2GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS2 >=", value, "picAddress2");
            return (Criteria) this;
        }

        public Criteria andPicAddress2LessThan(String value) {
            addCriterion("PIC_ADDRESS2 <", value, "picAddress2");
            return (Criteria) this;
        }

        public Criteria andPicAddress2LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS2 <=", value, "picAddress2");
            return (Criteria) this;
        }

        public Criteria andPicAddress2Like(String value) {
            addCriterion("PIC_ADDRESS2 like", value, "picAddress2");
            return (Criteria) this;
        }

        public Criteria andPicAddress2NotLike(String value) {
            addCriterion("PIC_ADDRESS2 not like", value, "picAddress2");
            return (Criteria) this;
        }

        public Criteria andPicAddress2In(List<String> values) {
            addCriterion("PIC_ADDRESS2 in", values, "picAddress2");
            return (Criteria) this;
        }

        public Criteria andPicAddress2NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS2 not in", values, "picAddress2");
            return (Criteria) this;
        }

        public Criteria andPicAddress2Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS2 between", value1, value2, "picAddress2");
            return (Criteria) this;
        }

        public Criteria andPicAddress2NotBetween(String value1, String value2) {
            addCriterion("PIC_ADDRESS2 not between", value1, value2, "picAddress2");
            return (Criteria) this;
        }

        public Criteria andpicAddress3IsNull() {
            addCriterion("PIC_ADDRESS3 is null");
            return (Criteria) this;
        }

        public Criteria andpicAddress3IsNotNull() {
            addCriterion("PIC_ADDRESS3 is not null");
            return (Criteria) this;
        }

        public Criteria andpicAddress3EqualTo(String value) {
            addCriterion("PIC_ADDRESS3 =", value, "picAddress3");
            return (Criteria) this;
        }

        public Criteria andpicAddress3NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS3 <>", value, "picAddress3");
            return (Criteria) this;
        }

        public Criteria andpicAddress3GreaterThan(String value) {
            addCriterion("PIC_ADDRESS3 >", value, "picAddress3");
            return (Criteria) this;
        }

        public Criteria andpicAddress3GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS3 >=", value, "picAddress3");
            return (Criteria) this;
        }

        public Criteria andpicAddress3LessThan(String value) {
            addCriterion("PIC_ADDRESS3 <", value, "picAddress3");
            return (Criteria) this;
        }

        public Criteria andpicAddress3LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS3 <=", value, "picAddress3");
            return (Criteria) this;
        }

        public Criteria andpicAddress3Like(String value) {
            addCriterion("PIC_ADDRESS3 like", value, "picAddress3");
            return (Criteria) this;
        }

        public Criteria andpicAddress3NotLike(String value) {
            addCriterion("PIC_ADDRESS3 not like", value, "picAddress3");
            return (Criteria) this;
        }

        public Criteria andpicAddress3In(List<String> values) {
            addCriterion("PIC_ADDRESS3 in", values, "picAddress3");
            return (Criteria) this;
        }

        public Criteria andpicAddress3NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS3 not in", values, "picAddress3");
            return (Criteria) this;
        }

        public Criteria andpicAddress3Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS3 between", value1, value2, "picAddress3");
            return (Criteria) this;
        }

        public Criteria andpicAddress3NotBetween(String value1, String value2) {
            addCriterion("PIC_ADDRESS3 not between", value1, value2, "picAddress3");
            return (Criteria) this;
        }

        public Criteria andpicAddress4IsNull() {
            addCriterion("PIC_ADDRESS4 is null");
            return (Criteria) this;
        }

        public Criteria andpicAddress4IsNotNull() {
            addCriterion("PIC_ADDRESS4 is not null");
            return (Criteria) this;
        }

        public Criteria andpicAddress4EqualTo(String value) {
            addCriterion("PIC_ADDRESS4 =", value, "picAddress4");
            return (Criteria) this;
        }

        public Criteria andpicAddress4NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS4 <>", value, "picAddress4");
            return (Criteria) this;
        }

        public Criteria andpicAddress4GreaterThan(String value) {
            addCriterion("PIC_ADDRESS4 >", value, "picAddress4");
            return (Criteria) this;
        }

        public Criteria andpicAddress4GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS4 >=", value, "picAddress4");
            return (Criteria) this;
        }

        public Criteria andpicAddress4LessThan(String value) {
            addCriterion("PIC_ADDRESS4 <", value, "picAddress4");
            return (Criteria) this;
        }

        public Criteria andpicAddress4LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS4 <=", value, "picAddress4");
            return (Criteria) this;
        }

        public Criteria andpicAddress4Like(String value) {
            addCriterion("PIC_ADDRESS4 like", value, "picAddress4");
            return (Criteria) this;
        }

        public Criteria andpicAddress4NotLike(String value) {
            addCriterion("PIC_ADDRESS4 not like", value, "picAddress4");
            return (Criteria) this;
        }

        public Criteria andpicAddress4In(List<String> values) {
            addCriterion("PIC_ADDRESS4 in", values, "picAddress4");
            return (Criteria) this;
        }

        public Criteria andpicAddress4NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS4 not in", values, "picAddress4");
            return (Criteria) this;
        }

        public Criteria andpicAddress4Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS4 between", value1, value2, "picAddress4");
            return (Criteria) this;
        }

        public Criteria andpicAddress4NotBetween(String value1, String value2) {
            addCriterion("PIC_ADDRESS4 not between", value1, value2, "picAddress4");
            return (Criteria) this;
        }

        public Criteria andPicAddress5IsNull() {
            addCriterion("PIC_ADDRESS5 is null");
            return (Criteria) this;
        }

        public Criteria andPicAddress5IsNotNull() {
            addCriterion("PIC_ADDRESS5 is not null");
            return (Criteria) this;
        }

        public Criteria andPicAddress5EqualTo(String value) {
            addCriterion("PIC_ADDRESS5 =", value, "picAddress5");
            return (Criteria) this;
        }

        public Criteria andPicAddress5NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS5 <>", value, "picAddress5");
            return (Criteria) this;
        }

        public Criteria andPicAddress5GreaterThan(String value) {
            addCriterion("PIC_ADDRESS5 >", value, "picAddress5");
            return (Criteria) this;
        }

        public Criteria andPicAddress5GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS5 >=", value, "picAddress5");
            return (Criteria) this;
        }

        public Criteria andPicAddress5LessThan(String value) {
            addCriterion("PIC_ADDRESS5 <", value, "picAddress5");
            return (Criteria) this;
        }

        public Criteria andPicAddress5LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS5 <=", value, "picAddress5");
            return (Criteria) this;
        }

        public Criteria andPicAddress5Like(String value) {
            addCriterion("PIC_ADDRESS5 like", value, "picAddress5");
            return (Criteria) this;
        }

        public Criteria andPicAddress5NotLike(String value) {
            addCriterion("PIC_ADDRESS5 not like", value, "picAddress5");
            return (Criteria) this;
        }

        public Criteria andPicAddress5In(List<String> values) {
            addCriterion("PIC_ADDRESS5 in", values, "picAddress5");
            return (Criteria) this;
        }

        public Criteria andPicAddress5NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS5 not in", values, "picAddress5");
            return (Criteria) this;
        }

        public Criteria andPicAddress5Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS5 between", value1, value2, "picAddress5");
            return (Criteria) this;
        }

        public Criteria andPicAddress5NotBetween(String value1, String value2) {
            addCriterion("PIC_ADDRESS5 not between", value1, value2, "picAddress5");
            return (Criteria) this;
        }

        public Criteria andpicAddress6IsNull() {
            addCriterion("PIC_ADDRESS6 is null");
            return (Criteria) this;
        }

        public Criteria andpicAddress6IsNotNull() {
            addCriterion("PIC_ADDRESS6 is not null");
            return (Criteria) this;
        }

        public Criteria andpicAddress6EqualTo(String value) {
            addCriterion("PIC_ADDRESS6 =", value, "picAddress6");
            return (Criteria) this;
        }

        public Criteria andpicAddress6NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS6 <>", value, "picAddress6");
            return (Criteria) this;
        }

        public Criteria andpicAddress6GreaterThan(String value) {
            addCriterion("PIC_ADDRESS6 >", value, "picAddress6");
            return (Criteria) this;
        }

        public Criteria andpicAddress6GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS6 >=", value, "picAddress6");
            return (Criteria) this;
        }

        public Criteria andpicAddress6LessThan(String value) {
            addCriterion("PIC_ADDRESS6 <", value, "picAddress6");
            return (Criteria) this;
        }

        public Criteria andpicAddress6LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS6 <=", value, "picAddress6");
            return (Criteria) this;
        }

        public Criteria andpicAddress6Like(String value) {
            addCriterion("PIC_ADDRESS6 like", value, "picAddress6");
            return (Criteria) this;
        }

        public Criteria andpicAddress6NotLike(String value) {
            addCriterion("PIC_ADDRESS6 not like", value, "picAddress6");
            return (Criteria) this;
        }

        public Criteria andpicAddress6In(List<String> values) {
            addCriterion("PIC_ADDRESS6 in", values, "picAddress6");
            return (Criteria) this;
        }

        public Criteria andpicAddress6NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS6 not in", values, "picAddress6");
            return (Criteria) this;
        }

        public Criteria andpicAddress6Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS6 between", value1, value2, "picAddress6");
            return (Criteria) this;
        }

        public Criteria andpicAddress6NotBetween(String value1, String value2) {
            addCriterion("PIC_ADDRESS6 not between", value1, value2, "picAddress6");
            return (Criteria) this;
        }

        public Criteria andpicAddress7IsNull() {
            addCriterion("PIC_ADDRESS7 is null");
            return (Criteria) this;
        }

        public Criteria andpicAddress7IsNotNull() {
            addCriterion("PIC_ADDRESS7 is not null");
            return (Criteria) this;
        }

        public Criteria andpicAddress7EqualTo(String value) {
            addCriterion("PIC_ADDRESS7 =", value, "picAddress7");
            return (Criteria) this;
        }

        public Criteria andpicAddress7NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS7 <>", value, "picAddress7");
            return (Criteria) this;
        }

        public Criteria andpicAddress7GreaterThan(String value) {
            addCriterion("PIC_ADDRESS7 >", value, "picAddress7");
            return (Criteria) this;
        }

        public Criteria andpicAddress7GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS7 >=", value, "picAddress7");
            return (Criteria) this;
        }

        public Criteria andpicAddress7LessThan(String value) {
            addCriterion("PIC_ADDRESS7 <", value, "picAddress7");
            return (Criteria) this;
        }

        public Criteria andpicAddress7LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS7 <=", value, "picAddress7");
            return (Criteria) this;
        }

        public Criteria andpicAddress7Like(String value) {
            addCriterion("PIC_ADDRESS7 like", value, "picAddress7");
            return (Criteria) this;
        }

        public Criteria andpicAddress7NotLike(String value) {
            addCriterion("PIC_ADDRESS7 not like", value, "picAddress7");
            return (Criteria) this;
        }

        public Criteria andpicAddress7In(List<String> values) {
            addCriterion("PIC_ADDRESS7 in", values, "picAddress7");
            return (Criteria) this;
        }

        public Criteria andpicAddress7NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS7 not in", values, "picAddress7");
            return (Criteria) this;
        }

        public Criteria andpicAddress7Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS7 between", value1, value2, "picAddress7");
            return (Criteria) this;
        }

        public Criteria andpicAddress7NotBetween(String value1, String value2) {   
        	addCriterion("PIC_ADDRESS7 not between", value1, value2, "picAddress7");
            return (Criteria) this;
        }

        public Criteria andpicAddress8IsNull() {
            addCriterion("PIC_ADDRESS8 is null");
            return (Criteria) this;
        }

        public Criteria andpicAddress8IsNotNull() {
            addCriterion("PIC_ADDRESS8 is not null");
            return (Criteria) this;
        }

        public Criteria andpicAddress8EqualTo(String value) {
            addCriterion("PIC_ADDRESS8 =", value, "picAddress8");
            return (Criteria) this;
        }

        public Criteria andpicAddress8NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS8 <>", value, "picAddress8");
            return (Criteria) this;
        }

        public Criteria andpicAddress8GreaterThan(String value) {
            addCriterion("PIC_ADDRESS8 >", value, "picAddress8");
            return (Criteria) this;
        }

        public Criteria andpicAddress8GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS8 >=", value, "picAddress8");
            return (Criteria) this;
        }

        public Criteria andpicAddress8LessThan(String value) {
            addCriterion("PIC_ADDRESS8 <", value, "picAddress8");
            return (Criteria) this;
        }

        public Criteria andpicAddress8LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS8 <=", value, "picAddress8");
            return (Criteria) this;
        }

        public Criteria andpicAddress8Like(String value) {
            addCriterion("PIC_ADDRESS8 like", value, "picAddress8");
            return (Criteria) this;
        }

        public Criteria andpicAddress8NotLike(String value) {
            addCriterion("PIC_ADDRESS8 not like", value, "picAddress8");
            return (Criteria) this;
        }

        public Criteria andpicAddress8In(List<String> values) {
            addCriterion("PIC_ADDRESS8 in", values, "picAddress8");
            return (Criteria) this;
        }

        public Criteria andpicAddress8NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS8 not in", values, "picAddress8");
            return (Criteria) this;
        }

        public Criteria andpicAddress8Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS8 between", value1, value2, "picAddress8");
            return (Criteria) this;
        }

        public Criteria andpicAddress8NotBetween(String value1, String value2) {
            addCriterion("PIC_ADDRESS8 not between", value1, value2, "picAddress8");
            return (Criteria) this;
        }

        public Criteria andPicAddress9IsNull() {
            addCriterion("PIC_ADDRESS9 is null");
            return (Criteria) this;
        }

        public Criteria andPicAddress9IsNotNull() {
            addCriterion("PIC_ADDRESS9 is not null");
            return (Criteria) this;
        }

        public Criteria andPicAddress9EqualTo(String value) {
            addCriterion("PIC_ADDRESS9 =", value, "picAddress9");
            return (Criteria) this;
        }

        public Criteria andPicAddress9NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS9 <>", value, "picAddress9");
            return (Criteria) this;
        }

        public Criteria andPicAddress9GreaterThan(String value) {
            addCriterion("PIC_ADDRESS9 >", value, "picAddress9");
            return (Criteria) this;
        }

        public Criteria andPicAddress9GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS9 >=", value, "picAddress9");
            return (Criteria) this;
        }

        public Criteria andPicAddress9LessThan(String value) {
            addCriterion("PIC_ADDRESS9 <", value, "picAddress9");
            return (Criteria) this;
        }

        public Criteria andPicAddress9LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS9 <=", value, "picAddress9");
            return (Criteria) this;
        }

        public Criteria andPicAddress9Like(String value) {
            addCriterion("PIC_ADDRESS9 like", value, "picAddress9");
            return (Criteria) this;
        }

        public Criteria andPicAddress9NotLike(String value) {
            addCriterion("PIC_ADDRESS9 not like", value, "picAddress9");
            return (Criteria) this;
        }

        public Criteria andPicAddress9In(List<String> values) {
            addCriterion("PIC_ADDRESS9 in", values, "picAddress9");
            return (Criteria) this;
        }

        public Criteria andPicAddress9NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS9 not in", values, "picAddress9");
            return (Criteria) this;
        }

        public Criteria andPicAddress9Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS9 between", value1, value2, "picAddress9");
            return (Criteria) this;
        }

        public Criteria andPicAddress9NotBetween(String value1, String value2) {
            addCriterion("PIC_ADDRESS9 not between", value1, value2, "picAddress9");
            return (Criteria) this;
        }

        public Criteria andpicAddress10IsNull() {
            addCriterion("PIC_ADDRESS10 is null");
            return (Criteria) this;
        }

        public Criteria andpicAddress10IsNotNull() {
            addCriterion("PIC_ADDRESS10 is not null");
            return (Criteria) this;
        }

        public Criteria andpicAddress10EqualTo(String value) {
            addCriterion("PIC_ADDRESS10 =", value, "picAddress10");
            return (Criteria) this;
        }

        public Criteria andpicAddress10NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS10 <>", value, "picAddress10");
            return (Criteria) this;
        }

        public Criteria andpicAddress10GreaterThan(String value) {
            addCriterion("PIC_ADDRESS10 >", value, "picAddress10");
            return (Criteria) this;
        }

        public Criteria andpicAddress10GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS10 >=", value, "picAddress10");
            return (Criteria) this;
        }

        public Criteria andpicAddress10LessThan(String value) {
            addCriterion("PIC_ADDRESS10 <", value, "picAddress10");
            return (Criteria) this;
        }

        public Criteria andpicAddress10LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS10 <=", value, "picAddress10");
            return (Criteria) this;
        }

        public Criteria andpicAddress10Like(String value) {
            addCriterion("PIC_ADDRESS10 like", value, "picAddress10");
            return (Criteria) this;
        }

        public Criteria andpicAddress10NotLike(String value) {
            addCriterion("PIC_ADDRESS10 not like", value, "picAddress10");
            return (Criteria) this;
        }

        public Criteria andpicAddress10In(List<String> values) {
            addCriterion("PIC_ADDRESS10 in", values, "picAddress10");
            return (Criteria) this;
        }

        public Criteria andpicAddress10NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS10 not in", values, "picAddress10");
            return (Criteria) this;
        }

        public Criteria andpicAddress10Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS10 between", value1, value2, "picAddress10");
            return (Criteria) this;
        }

        public Criteria andpicAddress10NotBetween(String value1, String value2) {
            addCriterion("PIC_ADDRESS10 not between", value1, value2, "picAddress10");
            return (Criteria) this;
        }

        public Criteria andpicAddress11IsNull() {
            addCriterion("PIC_ADDRESS11 is null");
            return (Criteria) this;
        }

        public Criteria andpicAddress11IsNotNull() {
            addCriterion("PIC_ADDRESS11 is not null");
            return (Criteria) this;
        }

        public Criteria andpicAddress11EqualTo(String value) {
            addCriterion("PIC_ADDRESS11 =", value, "picAddress11");
            return (Criteria) this;
        }

        public Criteria andpicAddress11NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS11 <>", value, "picAddress11");
            return (Criteria) this;
        }

        public Criteria andpicAddress11GreaterThan(String value) {
            addCriterion("PIC_ADDRESS11 >", value, "picAddress11");
            return (Criteria) this;
        }

        public Criteria andpicAddress11GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS11 >=", value, "picAddress11");
            return (Criteria) this;
        }

        public Criteria andpicAddress11LessThan(String value) {
            addCriterion("PIC_ADDRESS11 <", value, "picAddress11");
            return (Criteria) this;
        }

        public Criteria andpicAddress11LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS11 <=", value, "picAddress11");
            return (Criteria) this;
        }

        public Criteria andpicAddress11Like(String value) {
            addCriterion("PIC_ADDRESS11 like", value, "picAddress11");
            return (Criteria) this;
        }

        public Criteria andpicAddress11NotLike(String value) {
            addCriterion("PIC_ADDRESS11 not like", value, "picAddress11");
            return (Criteria) this;
        }

        public Criteria andpicAddress11In(List<String> values) {
            addCriterion("PIC_ADDRESS11 in", values, "picAddress11");
            return (Criteria) this;
        }

        public Criteria andpicAddress11NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS11 not in", values, "picAddress11");
            return (Criteria) this;
        }

        public Criteria andpicAddress11Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS11 between", value1, value2, "picAddress11");
            return (Criteria) this;
        }

        public Criteria andpicAddress11NotBetween(String value1, String value2) {     
        	addCriterion("PIC_ADDRESS11 not between", value1, value2, "picAddress11");
            return (Criteria) this;
        }

        public Criteria andpicAddress12IsNull() {
            addCriterion("PIC_ADDRESS12 is null");
            return (Criteria) this;
        }

        public Criteria andpicAddress12IsNotNull() {
            addCriterion("PIC_ADDRESS12 is not null");
            return (Criteria) this;
        }

        public Criteria andpicAddress12EqualTo(String value) {
            addCriterion("PIC_ADDRESS12 =", value, "picAddress12");
            return (Criteria) this;
        }

        public Criteria andpicAddress12NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS12 <>", value, "picAddress12");
            return (Criteria) this;
        }

        public Criteria andpicAddress12GreaterThan(String value) {
            addCriterion("PIC_ADDRESS12 >", value, "picAddress12");
            return (Criteria) this;
        }

        public Criteria andpicAddress12GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS12 >=", value, "picAddress12");
            return (Criteria) this;
        }

        public Criteria andpicAddress12LessThan(String value) {
            addCriterion("PIC_ADDRESS12 <", value, "picAddress12");
            return (Criteria) this;
        }

        public Criteria andpicAddress12LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS12 <=", value, "picAddress12");
            return (Criteria) this;
        }

        public Criteria andpicAddress12Like(String value) {
            addCriterion("PIC_ADDRESS12 like", value, "picAddress12");
            return (Criteria) this;
        }

        public Criteria andpicAddress12NotLike(String value) {
            addCriterion("PIC_ADDRESS12 not like", value, "picAddress12");
            return (Criteria) this;
        }

        public Criteria andpicAddress12In(List<String> values) {
            addCriterion("PIC_ADDRESS12 in", values, "picAddress12");
            return (Criteria) this;
        }

        public Criteria andpicAddress12NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS12 not in", values, "picAddress12");
            return (Criteria) this;
        }

        public Criteria andpicAddress12Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS12 between", value1, value2, "picAddress12");
            return (Criteria) this;
        }

        public Criteria andpicAddress12NotBetween(String value1, String value2) {
            addCriterion("PIC_ADDRESS12 not between", value1, value2, "picAddress12");
            return (Criteria) this;
        }

        public Criteria andpicAddress13IsNull() {
            addCriterion("PIC_ADDRESS13 is null");
            return (Criteria) this;
        }

        public Criteria andpicAddress13IsNotNull() {
            addCriterion("PIC_ADDRESS13 is not null");
            return (Criteria) this;
        }

        public Criteria andpicAddress13EqualTo(String value) {
            addCriterion("PIC_ADDRESS13 =", value, "picAddress13");
            return (Criteria) this;
        }

        public Criteria andpicAddress13NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS13 <>", value, "picAddress13");
            return (Criteria) this;
        }

        public Criteria andpicAddress13GreaterThan(String value) {
            addCriterion("PIC_ADDRESS13 >", value, "picAddress13");
            return (Criteria) this;
        }

        public Criteria andpicAddress13GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS13 >=", value, "picAddress13");
            return (Criteria) this;
        }

        public Criteria andpicAddress13LessThan(String value) {
            addCriterion("PIC_ADDRESS13 <", value, "picAddress13");
            return (Criteria) this;
        }

        public Criteria andpicAddress13LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS13 <=", value, "picAddress13");
            return (Criteria) this;
        }

        public Criteria andpicAddress13Like(String value) {
            addCriterion("PIC_ADDRESS13 like", value, "picAddress13");
            return (Criteria) this;
        }

        public Criteria andpicAddress13NotLike(String value) {
            addCriterion("PIC_ADDRESS13 not like", value, "picAddress13");
            return (Criteria) this;
        }

        public Criteria andpicAddress13In(List<String> values) {
            addCriterion("PIC_ADDRESS13 in", values, "picAddress13");
            return (Criteria) this;
        }

        public Criteria andpicAddress13NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS13 not in", values, "picAddress13");
            return (Criteria) this;
        }

        public Criteria andpicAddress13Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS13 between", value1, value2, "picAddress13");
            return (Criteria) this;
        }

        public Criteria andpicAddress13NotBetween(String value1, String value2) {
            addCriterion("PIC_ADDRESS13 not between", value1, value2, "picAddress13");
            return (Criteria) this;
        }

        public Criteria andPicAddress15IsNull() {
            addCriterion("PIC_ADDRESS15 is null");
            return (Criteria) this;
        }

        public Criteria andPicAddress15IsNotNull() {
            addCriterion("PIC_ADDRESS15 is not null");
            return (Criteria) this;
        }

        public Criteria andPicAddress15EqualTo(String value) {
            addCriterion("PIC_ADDRESS15 =", value, "picAddress15");
            return (Criteria) this;
        }

        public Criteria andPicAddress15NotEqualTo(String value) {
            addCriterion("PIC_ADDRESS15 <>", value, "picAddress15");
            return (Criteria) this;
        }

        public Criteria andPicAddress15GreaterThan(String value) {
            addCriterion("PIC_ADDRESS15 >", value, "picAddress15");
            return (Criteria) this;
        }

        public Criteria andPicAddress15GreaterThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS15 >=", value, "picAddress15");
            return (Criteria) this;
        }

        public Criteria andPicAddress15LessThan(String value) {
            addCriterion("PIC_ADDRESS15 <", value, "picAddress15");
            return (Criteria) this;
        }

        public Criteria andPicAddress15LessThanOrEqualTo(String value) {
            addCriterion("PIC_ADDRESS15 <=", value, "picAddress15");
            return (Criteria) this;
        }

        public Criteria andPicAddress15Like(String value) {
            addCriterion("PIC_ADDRESS15 like", value, "picAddress15");
            return (Criteria) this;
        }

        public Criteria andPicAddress15NotLike(String value) {
            addCriterion("PIC_ADDRESS15 not like", value, "picAddress15");
            return (Criteria) this;
        }

        public Criteria andPicAddress15In(List<String> values) {
            addCriterion("PIC_ADDRESS15 in", values, "picAddress15");
            return (Criteria) this;
        }

        public Criteria andPicAddress15NotIn(List<String> values) {
            addCriterion("PIC_ADDRESS15 not in", values, "picAddress15");
            return (Criteria) this;
        }

        public Criteria andPicAddress15Between(String value1, String value2) {
            addCriterion("PIC_ADDRESS15 between", value1, value2, "picAddress15");
            return (Criteria) this;
        }

        public Criteria andPicAddress15NotBetween(String value1, String value2) {
            addCriterion("PIC_ADDRESS15 not between", value1, value2, "picAddress15");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_MER_FILE_INFO
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}