package com.allcheer.bpos.entity;

public class TblMerRelevanceMccDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_MER_RELEVANCE_MCC.MCC_ID
     *
     * @mbggenerated
     */
    private String mccId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_MER_RELEVANCE_MCC.MCC_VALUE
     *
     * @mbggenerated
     */
    private String mccValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_MER_RELEVANCE_MCC.MCC_DESP
     *
     * @mbggenerated
     */
    private String mccDesp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_MER_RELEVANCE_MCC.MER_ID
     *
     * @mbggenerated
     */
    private String merId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_MER_RELEVANCE_MCC.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_MER_RELEVANCE_MCC.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_MER_RELEVANCE_MCC.UPDATE_TIME
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_MER_RELEVANCE_MCC.MCC_ID
     *
     * @return the value of TBL_MER_RELEVANCE_MCC.MCC_ID
     *
     * @mbggenerated
     */
    public String getMccId() {
        return mccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_MER_RELEVANCE_MCC.MCC_ID
     *
     * @param mccId the value for TBL_MER_RELEVANCE_MCC.MCC_ID
     *
     * @mbggenerated
     */
    public void setMccId(String mccId) {
        this.mccId = mccId == null ? null : mccId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_MER_RELEVANCE_MCC.MCC_VALUE
     *
     * @return the value of TBL_MER_RELEVANCE_MCC.MCC_VALUE
     *
     * @mbggenerated
     */
    public String getMccValue() {
        return mccValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_MER_RELEVANCE_MCC.MCC_VALUE
     *
     * @param mccValue the value for TBL_MER_RELEVANCE_MCC.MCC_VALUE
     *
     * @mbggenerated
     */
    public void setMccValue(String mccValue) {
        this.mccValue = mccValue == null ? null : mccValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_MER_RELEVANCE_MCC.MCC_DESP
     *
     * @return the value of TBL_MER_RELEVANCE_MCC.MCC_DESP
     *
     * @mbggenerated
     */
    public String getMccDesp() {
        return mccDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_MER_RELEVANCE_MCC.MCC_DESP
     *
     * @param mccDesp the value for TBL_MER_RELEVANCE_MCC.MCC_DESP
     *
     * @mbggenerated
     */
    public void setMccDesp(String mccDesp) {
        this.mccDesp = mccDesp == null ? null : mccDesp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_MER_RELEVANCE_MCC.MER_ID
     *
     * @return the value of TBL_MER_RELEVANCE_MCC.MER_ID
     *
     * @mbggenerated
     */
    public String getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_MER_RELEVANCE_MCC.MER_ID
     *
     * @param merId the value for TBL_MER_RELEVANCE_MCC.MER_ID
     *
     * @mbggenerated
     */
    public void setMerId(String merId) {
        this.merId = merId == null ? null : merId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_MER_RELEVANCE_MCC.CREATE_USER
     *
     * @return the value of TBL_MER_RELEVANCE_MCC.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_MER_RELEVANCE_MCC.CREATE_USER
     *
     * @param createUser the value for TBL_MER_RELEVANCE_MCC.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_MER_RELEVANCE_MCC.CREATE_TIME
     *
     * @return the value of TBL_MER_RELEVANCE_MCC.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_MER_RELEVANCE_MCC.CREATE_TIME
     *
     * @param createTime the value for TBL_MER_RELEVANCE_MCC.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_MER_RELEVANCE_MCC.UPDATE_TIME
     *
     * @return the value of TBL_MER_RELEVANCE_MCC.UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_MER_RELEVANCE_MCC.UPDATE_TIME
     *
     * @param updateTime the value for TBL_MER_RELEVANCE_MCC.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}