package com.allcheer.bpos.entity;

public class TblOnlineUserLoginDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ONLINE_USER_LOGIN.USR_ID
     *
     * @mbggenerated
     */
    private String usrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ONLINE_USER_LOGIN.USR_NAME
     *
     * @mbggenerated
     */
    private String usrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ONLINE_USER_LOGIN.USR_PWD
     *
     * @mbggenerated
     */
    private String usrPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ONLINE_USER_LOGIN.USR_REMARK
     *
     * @mbggenerated
     */
    private String usrRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ONLINE_USER_LOGIN.USR_DISABLE_TAG
     *
     * @mbggenerated
     */
    private String usrDisableTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ONLINE_USER_LOGIN.USR_EMAIL
     *
     * @mbggenerated
     */
    private String usrEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ONLINE_USER_LOGIN.USR_CREATE_BY
     *
     * @mbggenerated
     */
    private String usrCreateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ONLINE_USER_LOGIN.USR_CREATE_DATE
     *
     * @mbggenerated
     */
    private String usrCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ONLINE_USER_LOGIN.USR_UPDATE_BY
     *
     * @mbggenerated
     */
    private String usrUpdateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ONLINE_USER_LOGIN.USR_UPDATE_DATE
     *
     * @mbggenerated
     */
    private String usrUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ONLINE_USER_LOGIN.USR_TYPE
     *
     * @mbggenerated
     */
    private String usrType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ONLINE_USER_LOGIN.USR_ID
     *
     * @return the value of TBL_ONLINE_USER_LOGIN.USR_ID
     *
     * @mbggenerated
     */
    public String getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ONLINE_USER_LOGIN.USR_ID
     *
     * @param usrId the value for TBL_ONLINE_USER_LOGIN.USR_ID
     *
     * @mbggenerated
     */
    public void setUsrId(String usrId) {
        this.usrId = usrId == null ? null : usrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ONLINE_USER_LOGIN.USR_NAME
     *
     * @return the value of TBL_ONLINE_USER_LOGIN.USR_NAME
     *
     * @mbggenerated
     */
    public String getUsrName() {
        return usrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ONLINE_USER_LOGIN.USR_NAME
     *
     * @param usrName the value for TBL_ONLINE_USER_LOGIN.USR_NAME
     *
     * @mbggenerated
     */
    public void setUsrName(String usrName) {
        this.usrName = usrName == null ? null : usrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ONLINE_USER_LOGIN.USR_PWD
     *
     * @return the value of TBL_ONLINE_USER_LOGIN.USR_PWD
     *
     * @mbggenerated
     */
    public String getUsrPwd() {
        return usrPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ONLINE_USER_LOGIN.USR_PWD
     *
     * @param usrPwd the value for TBL_ONLINE_USER_LOGIN.USR_PWD
     *
     * @mbggenerated
     */
    public void setUsrPwd(String usrPwd) {
        this.usrPwd = usrPwd == null ? null : usrPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ONLINE_USER_LOGIN.USR_REMARK
     *
     * @return the value of TBL_ONLINE_USER_LOGIN.USR_REMARK
     *
     * @mbggenerated
     */
    public String getUsrRemark() {
        return usrRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ONLINE_USER_LOGIN.USR_REMARK
     *
     * @param usrRemark the value for TBL_ONLINE_USER_LOGIN.USR_REMARK
     *
     * @mbggenerated
     */
    public void setUsrRemark(String usrRemark) {
        this.usrRemark = usrRemark == null ? null : usrRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ONLINE_USER_LOGIN.USR_DISABLE_TAG
     *
     * @return the value of TBL_ONLINE_USER_LOGIN.USR_DISABLE_TAG
     *
     * @mbggenerated
     */
    public String getUsrDisableTag() {
        return usrDisableTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ONLINE_USER_LOGIN.USR_DISABLE_TAG
     *
     * @param usrDisableTag the value for TBL_ONLINE_USER_LOGIN.USR_DISABLE_TAG
     *
     * @mbggenerated
     */
    public void setUsrDisableTag(String usrDisableTag) {
        this.usrDisableTag = usrDisableTag == null ? null : usrDisableTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ONLINE_USER_LOGIN.USR_EMAIL
     *
     * @return the value of TBL_ONLINE_USER_LOGIN.USR_EMAIL
     *
     * @mbggenerated
     */
    public String getUsrEmail() {
        return usrEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ONLINE_USER_LOGIN.USR_EMAIL
     *
     * @param usrEmail the value for TBL_ONLINE_USER_LOGIN.USR_EMAIL
     *
     * @mbggenerated
     */
    public void setUsrEmail(String usrEmail) {
        this.usrEmail = usrEmail == null ? null : usrEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ONLINE_USER_LOGIN.USR_CREATE_BY
     *
     * @return the value of TBL_ONLINE_USER_LOGIN.USR_CREATE_BY
     *
     * @mbggenerated
     */
    public String getUsrCreateBy() {
        return usrCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ONLINE_USER_LOGIN.USR_CREATE_BY
     *
     * @param usrCreateBy the value for TBL_ONLINE_USER_LOGIN.USR_CREATE_BY
     *
     * @mbggenerated
     */
    public void setUsrCreateBy(String usrCreateBy) {
        this.usrCreateBy = usrCreateBy == null ? null : usrCreateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ONLINE_USER_LOGIN.USR_CREATE_DATE
     *
     * @return the value of TBL_ONLINE_USER_LOGIN.USR_CREATE_DATE
     *
     * @mbggenerated
     */
    public String getUsrCreateDate() {
        return usrCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ONLINE_USER_LOGIN.USR_CREATE_DATE
     *
     * @param usrCreateDate the value for TBL_ONLINE_USER_LOGIN.USR_CREATE_DATE
     *
     * @mbggenerated
     */
    public void setUsrCreateDate(String usrCreateDate) {
        this.usrCreateDate = usrCreateDate == null ? null : usrCreateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ONLINE_USER_LOGIN.USR_UPDATE_BY
     *
     * @return the value of TBL_ONLINE_USER_LOGIN.USR_UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUsrUpdateBy() {
        return usrUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ONLINE_USER_LOGIN.USR_UPDATE_BY
     *
     * @param usrUpdateBy the value for TBL_ONLINE_USER_LOGIN.USR_UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUsrUpdateBy(String usrUpdateBy) {
        this.usrUpdateBy = usrUpdateBy == null ? null : usrUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ONLINE_USER_LOGIN.USR_UPDATE_DATE
     *
     * @return the value of TBL_ONLINE_USER_LOGIN.USR_UPDATE_DATE
     *
     * @mbggenerated
     */
    public String getUsrUpdateDate() {
        return usrUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ONLINE_USER_LOGIN.USR_UPDATE_DATE
     *
     * @param usrUpdateDate the value for TBL_ONLINE_USER_LOGIN.USR_UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUsrUpdateDate(String usrUpdateDate) {
        this.usrUpdateDate = usrUpdateDate == null ? null : usrUpdateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ONLINE_USER_LOGIN.USR_TYPE
     *
     * @return the value of TBL_ONLINE_USER_LOGIN.USR_TYPE
     *
     * @mbggenerated
     */
    public String getUsrType() {
        return usrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ONLINE_USER_LOGIN.USR_TYPE
     *
     * @param usrType the value for TBL_ONLINE_USER_LOGIN.USR_TYPE
     *
     * @mbggenerated
     */
    public void setUsrType(String usrType) {
        this.usrType = usrType == null ? null : usrType.trim();
    }
}