package com.allcheer.bpos.entity;

public class TblProvDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_PROVINCE.PROVINCE_ID
     *
     * @mbggenerated
     */
    private String provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_PROVINCE.PROVINCE_NAME
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_PROVINCE.PROVINCE_ID
     *
     * @return the value of TBL_PROVINCE.PROVINCE_ID
     *
     * @mbggenerated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_PROVINCE.PROVINCE_ID
     *
     * @param provinceId the value for TBL_PROVINCE.PROVINCE_ID
     *
     * @mbggenerated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_PROVINCE.PROVINCE_NAME
     *
     * @return the value of TBL_PROVINCE.PROVINCE_NAME
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_PROVINCE.PROVINCE_NAME
     *
     * @param provinceName the value for TBL_PROVINCE.PROVINCE_NAME
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }
}