package com.allcheer.bpos.entity;

public class TblTermInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TERM_INFO.TERM_ID
     *
     * @mbggenerated
     */
    private String termId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TERM_INFO.TERM_NAME
     *
     * @mbggenerated
     */
    private String termName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TERM_INFO.TERM_TYPE
     *
     * @mbggenerated
     */
    private String termType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TERM_INFO.TERM_STAT
     *
     * @mbggenerated
     */
    private String termStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TERM_INFO.TERM_INSTALL_PROV
     *
     * @mbggenerated
     */
    private String termInstallProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TERM_INFO.TERM_INSTALL_CITY
     *
     * @mbggenerated
     */
    private String termInstallCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TERM_INFO.TERM_INSTALL_COUNTY
     *
     * @mbggenerated
     */
    private String termInstallCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TERM_INFO.TERM_INSTALL_ADDRESS
     *
     * @mbggenerated
     */
    private String termInstallAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TERM_INFO.TERM_SN
     *
     * @mbggenerated
     */
    private String termSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TERM_INFO.MER_ID
     *
     * @mbggenerated
     */
    private String merId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TERM_INFO.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TERM_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TERM_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TERM_INFO.TERM_ID
     *
     * @return the value of TBL_TERM_INFO.TERM_ID
     *
     * @mbggenerated
     */
    public String getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TERM_INFO.TERM_ID
     *
     * @param termId the value for TBL_TERM_INFO.TERM_ID
     *
     * @mbggenerated
     */
    public void setTermId(String termId) {
        this.termId = termId == null ? null : termId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TERM_INFO.TERM_NAME
     *
     * @return the value of TBL_TERM_INFO.TERM_NAME
     *
     * @mbggenerated
     */
    public String getTermName() {
        return termName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TERM_INFO.TERM_NAME
     *
     * @param termName the value for TBL_TERM_INFO.TERM_NAME
     *
     * @mbggenerated
     */
    public void setTermName(String termName) {
        this.termName = termName == null ? null : termName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TERM_INFO.TERM_TYPE
     *
     * @return the value of TBL_TERM_INFO.TERM_TYPE
     *
     * @mbggenerated
     */
    public String getTermType() {
        return termType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TERM_INFO.TERM_TYPE
     *
     * @param termType the value for TBL_TERM_INFO.TERM_TYPE
     *
     * @mbggenerated
     */
    public void setTermType(String termType) {
        this.termType = termType == null ? null : termType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TERM_INFO.TERM_STAT
     *
     * @return the value of TBL_TERM_INFO.TERM_STAT
     *
     * @mbggenerated
     */
    public String getTermStat() {
        return termStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TERM_INFO.TERM_STAT
     *
     * @param termStat the value for TBL_TERM_INFO.TERM_STAT
     *
     * @mbggenerated
     */
    public void setTermStat(String termStat) {
        this.termStat = termStat == null ? null : termStat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TERM_INFO.TERM_INSTALL_PROV
     *
     * @return the value of TBL_TERM_INFO.TERM_INSTALL_PROV
     *
     * @mbggenerated
     */
    public String getTermInstallProv() {
        return termInstallProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TERM_INFO.TERM_INSTALL_PROV
     *
     * @param termInstallProv the value for TBL_TERM_INFO.TERM_INSTALL_PROV
     *
     * @mbggenerated
     */
    public void setTermInstallProv(String termInstallProv) {
        this.termInstallProv = termInstallProv == null ? null : termInstallProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TERM_INFO.TERM_INSTALL_CITY
     *
     * @return the value of TBL_TERM_INFO.TERM_INSTALL_CITY
     *
     * @mbggenerated
     */
    public String getTermInstallCity() {
        return termInstallCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TERM_INFO.TERM_INSTALL_CITY
     *
     * @param termInstallCity the value for TBL_TERM_INFO.TERM_INSTALL_CITY
     *
     * @mbggenerated
     */
    public void setTermInstallCity(String termInstallCity) {
        this.termInstallCity = termInstallCity == null ? null : termInstallCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TERM_INFO.TERM_INSTALL_COUNTY
     *
     * @return the value of TBL_TERM_INFO.TERM_INSTALL_COUNTY
     *
     * @mbggenerated
     */
    public String getTermInstallCounty() {
        return termInstallCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TERM_INFO.TERM_INSTALL_COUNTY
     *
     * @param termInstallCounty the value for TBL_TERM_INFO.TERM_INSTALL_COUNTY
     *
     * @mbggenerated
     */
    public void setTermInstallCounty(String termInstallCounty) {
        this.termInstallCounty = termInstallCounty == null ? null : termInstallCounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TERM_INFO.TERM_INSTALL_ADDRESS
     *
     * @return the value of TBL_TERM_INFO.TERM_INSTALL_ADDRESS
     *
     * @mbggenerated
     */
    public String getTermInstallAddress() {
        return termInstallAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TERM_INFO.TERM_INSTALL_ADDRESS
     *
     * @param termInstallAddress the value for TBL_TERM_INFO.TERM_INSTALL_ADDRESS
     *
     * @mbggenerated
     */
    public void setTermInstallAddress(String termInstallAddress) {
        this.termInstallAddress = termInstallAddress == null ? null : termInstallAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TERM_INFO.TERM_SN
     *
     * @return the value of TBL_TERM_INFO.TERM_SN
     *
     * @mbggenerated
     */
    public String getTermSn() {
        return termSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TERM_INFO.TERM_SN
     *
     * @param termSn the value for TBL_TERM_INFO.TERM_SN
     *
     * @mbggenerated
     */
    public void setTermSn(String termSn) {
        this.termSn = termSn == null ? null : termSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TERM_INFO.MER_ID
     *
     * @return the value of TBL_TERM_INFO.MER_ID
     *
     * @mbggenerated
     */
    public String getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TERM_INFO.MER_ID
     *
     * @param merId the value for TBL_TERM_INFO.MER_ID
     *
     * @mbggenerated
     */
    public void setMerId(String merId) {
        this.merId = merId == null ? null : merId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TERM_INFO.USER_NAME
     *
     * @return the value of TBL_TERM_INFO.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TERM_INFO.USER_NAME
     *
     * @param userName the value for TBL_TERM_INFO.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TERM_INFO.UPDATE_TIME
     *
     * @return the value of TBL_TERM_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TERM_INFO.UPDATE_TIME
     *
     * @param updateTime the value for TBL_TERM_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TERM_INFO.CREATE_TIME
     *
     * @return the value of TBL_TERM_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TERM_INFO.CREATE_TIME
     *
     * @param createTime the value for TBL_TERM_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}