package com.allcheer.bpos.entity;

public class TblU1CheckFileDetailDOKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_U1_CHECK_FILE_DETAIL.TERMTRC 
     *
     * @mbggenerated
     */
    private String termtrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_U1_CHECK_FILE_DETAIL.REFNUM
     *
     * @mbggenerated
     */
    private String refnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_U1_CHECK_FILE_DETAIL.AUTHID
     *
     * @mbggenerated
     */
    private String authid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_U1_CHECK_FILE_DETAIL.TERMTRC 
     *
     * @return the value of TBL_U1_CHECK_FILE_DETAIL.TERMTRC 
     *
     * @mbggenerated
     */
    public String getTermtrc() {
        return termtrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_U1_CHECK_FILE_DETAIL.TERMTRC 
     *
     * @param termtrc the value for TBL_U1_CHECK_FILE_DETAIL.TERMTRC 
     *
     * @mbggenerated
     */
    public void setTermtrc(String termtrc) {
        this.termtrc = termtrc == null ? null : termtrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_U1_CHECK_FILE_DETAIL.REFNUM
     *
     * @return the value of TBL_U1_CHECK_FILE_DETAIL.REFNUM
     *
     * @mbggenerated
     */
    public String getRefnum() {
        return refnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_U1_CHECK_FILE_DETAIL.REFNUM
     *
     * @param refnum the value for TBL_U1_CHECK_FILE_DETAIL.REFNUM
     *
     * @mbggenerated
     */
    public void setRefnum(String refnum) {
        this.refnum = refnum == null ? null : refnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_U1_CHECK_FILE_DETAIL.AUTHID
     *
     * @return the value of TBL_U1_CHECK_FILE_DETAIL.AUTHID
     *
     * @mbggenerated
     */
    public String getAuthid() {
        return authid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_U1_CHECK_FILE_DETAIL.AUTHID
     *
     * @param authid the value for TBL_U1_CHECK_FILE_DETAIL.AUTHID
     *
     * @mbggenerated
     */
    public void setAuthid(String authid) {
        this.authid = authid == null ? null : authid.trim();
    }
}