package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.ACCOUNTDO;
import com.allcheer.bpos.entity.ACCOUNTDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ACCOUNTDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated
     */
    int countByExample(ACCOUNTDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated
     */
    int deleteByExample(ACCOUNTDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated
     */
    int insert(ACCOUNTDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated
     */
    int insertSelective(ACCOUNTDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated
     */
    List<ACCOUNTDO> selectByExample(ACCOUNTDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ACCOUNTDO record, @Param("example") ACCOUNTDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ACCOUNTDO record, @Param("example") ACCOUNTDOExample example);
}