package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.LeShuaMerFuncInfoDO;
import com.allcheer.bpos.entity.LeShuaMerFuncInfoDOExample;
import com.allcheer.bpos.entity.LeShuaMerFuncInfoDOKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LeShuaMerFuncInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LE_SHUA_MER_FUNC_INFO
     *
     * @mbggenerated
     */
    int countByExample(LeShuaMerFuncInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LE_SHUA_MER_FUNC_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(LeShuaMerFuncInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LE_SHUA_MER_FUNC_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(LeShuaMerFuncInfoDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LE_SHUA_MER_FUNC_INFO
     *
     * @mbggenerated
     */
    int insert(LeShuaMerFuncInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LE_SHUA_MER_FUNC_INFO
     *
     * @mbggenerated
     */
    int insertSelective(LeShuaMerFuncInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LE_SHUA_MER_FUNC_INFO
     *
     * @mbggenerated
     */
    List<LeShuaMerFuncInfoDO> selectByExample(LeShuaMerFuncInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LE_SHUA_MER_FUNC_INFO
     *
     * @mbggenerated
     */
    LeShuaMerFuncInfoDO selectByPrimaryKey(LeShuaMerFuncInfoDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LE_SHUA_MER_FUNC_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LeShuaMerFuncInfoDO record, @Param("example") LeShuaMerFuncInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LE_SHUA_MER_FUNC_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LeShuaMerFuncInfoDO record, @Param("example") LeShuaMerFuncInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LE_SHUA_MER_FUNC_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LeShuaMerFuncInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LE_SHUA_MER_FUNC_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LeShuaMerFuncInfoDO record);
}