package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblAgentFeeDo;
import com.allcheer.bpos.entity.TblAgentFeeDoExample;
import com.allcheer.bpos.entity.TblAgentFeeDoKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblAgentFeeDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_FEE
     *
     * @mbggenerated
     */
    int countByExample(TblAgentFeeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_FEE
     *
     * @mbggenerated
     */
    int deleteByExample(TblAgentFeeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_FEE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TblAgentFeeDoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_FEE
     *
     * @mbggenerated
     */
    int insert(TblAgentFeeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_FEE
     *
     * @mbggenerated
     */
    int insertSelective(TblAgentFeeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_FEE
     *
     * @mbggenerated
     */
    List<TblAgentFeeDo> selectByExample(TblAgentFeeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_FEE
     *
     * @mbggenerated
     */
    TblAgentFeeDo selectByPrimaryKey(TblAgentFeeDoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_FEE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblAgentFeeDo record, @Param("example") TblAgentFeeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_FEE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblAgentFeeDo record, @Param("example") TblAgentFeeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_FEE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblAgentFeeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_FEE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblAgentFeeDo record);
}