package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblAddressCodeMoreDO;
import com.allcheer.bpos.entity.TblAddressCodeMoreDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblAddressCodeMoreDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ADDRESS_CODE_MORE
     *
     * @mbggenerated
     */
    int countByExample(TblAddressCodeMoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ADDRESS_CODE_MORE
     *
     * @mbggenerated
     */
    int deleteByExample(TblAddressCodeMoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ADDRESS_CODE_MORE
     *
     * @mbggenerated
     */
    int insert(TblAddressCodeMoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ADDRESS_CODE_MORE
     *
     * @mbggenerated
     */
    int insertSelective(TblAddressCodeMoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ADDRESS_CODE_MORE
     *
     * @mbggenerated
     */
    List<TblAddressCodeMoreDO> selectByExample(TblAddressCodeMoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ADDRESS_CODE_MORE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblAddressCodeMoreDO record, @Param("example") TblAddressCodeMoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ADDRESS_CODE_MORE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblAddressCodeMoreDO record, @Param("example") TblAddressCodeMoreDOExample example);
}