package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblAgentMerAddBatchDO;
import com.allcheer.bpos.entity.TblAgentMerAddBatchDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblAgentMerAddBatchDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int countByExample(TblAgentMerAddBatchDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(TblAgentMerAddBatchDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String batchNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int insert(TblAgentMerAddBatchDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int insertSelective(TblAgentMerAddBatchDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    List<TblAgentMerAddBatchDO> selectByExample(TblAgentMerAddBatchDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    TblAgentMerAddBatchDO selectByPrimaryKey(String batchNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblAgentMerAddBatchDO record, @Param("example") TblAgentMerAddBatchDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblAgentMerAddBatchDO record, @Param("example") TblAgentMerAddBatchDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblAgentMerAddBatchDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblAgentMerAddBatchDO record);
}