package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblAgentMerTermDo;
import com.allcheer.bpos.entity.TblAgentMerTermDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblAgentMerTermDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_TERM_REL
     *
     * @mbggenerated
     */
    int countByExample(TblAgentMerTermDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_TERM_REL
     *
     * @mbggenerated
     */
    int deleteByExample(TblAgentMerTermDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_TERM_REL
     *
     * @mbggenerated
     */
    int insert(TblAgentMerTermDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_TERM_REL
     *
     * @mbggenerated
     */
    int insertSelective(TblAgentMerTermDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_TERM_REL
     *
     * @mbggenerated
     */
    List<TblAgentMerTermDo> selectByExample(TblAgentMerTermDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_TERM_REL
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblAgentMerTermDo record, @Param("example") TblAgentMerTermDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGENT_MER_TERM_REL
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblAgentMerTermDo record, @Param("example") TblAgentMerTermDoExample example);
}