package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblAgentAuditRecordDo;
import com.allcheer.bpos.entity.TblAgentAuditRecordDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblAgentAuditRecordDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGNET_AUDIT_RECORD
     *
     * @mbggenerated
     */

    TblAgentAuditRecordDo selectByPrimaryKey(String id);
    int countByExample(TblAgentAuditRecordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGNET_AUDIT_RECORD
     *
     * @mbggenerated
     */
    int deleteByExample(TblAgentAuditRecordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGNET_AUDIT_RECORD
     *
     * @mbggenerated
     */
    int insert(TblAgentAuditRecordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGNET_AUDIT_RECORD
     *
     * @mbggenerated
     */
    int insertSelective(TblAgentAuditRecordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGNET_AUDIT_RECORD
     *
     * @mbggenerated
     */
    List<TblAgentAuditRecordDo> selectByExample(TblAgentAuditRecordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGNET_AUDIT_RECORD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblAgentAuditRecordDo record, @Param("example") TblAgentAuditRecordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_AGNET_AUDIT_RECORD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblAgentAuditRecordDo record, @Param("example") TblAgentAuditRecordDoExample example);
}