package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblBTSSysFunctionDO;
import com.allcheer.bpos.entity.TblBTSSysFunctionDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblBTSSysFunctionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_FUNCTION
     *
     * @mbggenerated
     */
    int countByExample(TblBTSSysFunctionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_FUNCTION
     *
     * @mbggenerated
     */
    int deleteByExample(TblBTSSysFunctionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_FUNCTION
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String funcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_FUNCTION
     *
     * @mbggenerated
     */
    int insert(TblBTSSysFunctionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_FUNCTION
     *
     * @mbggenerated
     */
    int insertSelective(TblBTSSysFunctionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_FUNCTION
     *
     * @mbggenerated
     */
    List<TblBTSSysFunctionDO> selectByExample(TblBTSSysFunctionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_FUNCTION
     *
     * @mbggenerated
     */
    TblBTSSysFunctionDO selectByPrimaryKey(String funcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_FUNCTION
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblBTSSysFunctionDO record, @Param("example") TblBTSSysFunctionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_FUNCTION
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblBTSSysFunctionDO record, @Param("example") TblBTSSysFunctionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_FUNCTION
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblBTSSysFunctionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_FUNCTION
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblBTSSysFunctionDO record);
}