package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblBankPosInfoDO;
import com.allcheer.bpos.entity.TblBankPosInfoDOExample;
import com.allcheer.bpos.entity.TblBankPosInfoDOKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblBankPosInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BANK_POS_INFO
     *
     * @mbggenerated
     */
    int countByExample(TblBankPosInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BANK_POS_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(TblBankPosInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BANK_POS_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TblBankPosInfoDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BANK_POS_INFO
     *
     * @mbggenerated
     */
    int insert(TblBankPosInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BANK_POS_INFO
     *
     * @mbggenerated
     */
    int insertSelective(TblBankPosInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BANK_POS_INFO
     *
     * @mbggenerated
     */
    List<TblBankPosInfoDO> selectByExample(TblBankPosInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BANK_POS_INFO
     *
     * @mbggenerated
     */
    TblBankPosInfoDO selectByPrimaryKey(TblBankPosInfoDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BANK_POS_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblBankPosInfoDO record, @Param("example") TblBankPosInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BANK_POS_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblBankPosInfoDO record, @Param("example") TblBankPosInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BANK_POS_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblBankPosInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BANK_POS_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblBankPosInfoDO record);
}