package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblBTSSysRoleFuncDO;
import com.allcheer.bpos.entity.TblBTSSysRoleFuncDOExample;
import com.allcheer.bpos.entity.TblBTSSysRoleFuncDOKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblBTSSysRoleFuncDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int countByExample(TblBTSSysRoleFuncDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int deleteByExample(TblBTSSysRoleFuncDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TblBTSSysRoleFuncDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int insert(TblBTSSysRoleFuncDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int insertSelective(TblBTSSysRoleFuncDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    List<TblBTSSysRoleFuncDO> selectByExample(TblBTSSysRoleFuncDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    TblBTSSysRoleFuncDO selectByPrimaryKey(TblBTSSysRoleFuncDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblBTSSysRoleFuncDO record, @Param("example") TblBTSSysRoleFuncDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblBTSSysRoleFuncDO record, @Param("example") TblBTSSysRoleFuncDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblBTSSysRoleFuncDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE_FUNC
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblBTSSysRoleFuncDO record);
}