package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblBtsMerRConfDO;
import com.allcheer.bpos.entity.TblBtsMerRConfDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblBtsMerRConfDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_MERR_CONF
     *
     * @mbggenerated
     */
    int countByExample(TblBtsMerRConfDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_MERR_CONF
     *
     * @mbggenerated
     */
    int deleteByExample(TblBtsMerRConfDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_MERR_CONF
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String merId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_MERR_CONF
     *
     * @mbggenerated
     */
    int insert(TblBtsMerRConfDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_MERR_CONF
     *
     * @mbggenerated
     */
    int insertSelective(TblBtsMerRConfDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_MERR_CONF
     *
     * @mbggenerated
     */
    List<TblBtsMerRConfDO> selectByExample(TblBtsMerRConfDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_MERR_CONF
     *
     * @mbggenerated
     */
    TblBtsMerRConfDO selectByPrimaryKey(String merId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_MERR_CONF
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblBtsMerRConfDO record, @Param("example") TblBtsMerRConfDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_MERR_CONF
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblBtsMerRConfDO record, @Param("example") TblBtsMerRConfDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_MERR_CONF
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblBtsMerRConfDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_MERR_CONF
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblBtsMerRConfDO record);
}