package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblCapitalClearingDo;
import com.allcheer.bpos.entity.TblCapitalClearingDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblCapitalClearingDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CAPITAL_CLEARING
     *
     * @mbggenerated
     */
    int countByExample(TblCapitalClearingDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CAPITAL_CLEARING
     *
     * @mbggenerated
     */
    int deleteByExample(TblCapitalClearingDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CAPITAL_CLEARING
     *
     * @mbggenerated
     */
    int insert(TblCapitalClearingDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CAPITAL_CLEARING
     *
     * @mbggenerated
     */
    int insertSelective(TblCapitalClearingDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CAPITAL_CLEARING
     *
     * @mbggenerated
     */
    List<TblCapitalClearingDo> selectByExample(TblCapitalClearingDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CAPITAL_CLEARING
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblCapitalClearingDo record, @Param("example") TblCapitalClearingDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CAPITAL_CLEARING
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblCapitalClearingDo record, @Param("example") TblCapitalClearingDoExample example);
}