package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblInstMerKeyInfoDO;
import com.allcheer.bpos.entity.TblInstMerKeyInfoDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblInstMerKeyInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_KEY_INFO
     *
     * @mbggenerated
     */
    int countByExample(TblInstMerKeyInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_KEY_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(TblInstMerKeyInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_KEY_INFO
     *
     * @mbggenerated
     */
    int insert(TblInstMerKeyInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_KEY_INFO
     *
     * @mbggenerated
     */
    int insertSelective(TblInstMerKeyInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_KEY_INFO
     *
     * @mbggenerated
     */
    List<TblInstMerKeyInfoDO> selectByExample(TblInstMerKeyInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_KEY_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblInstMerKeyInfoDO record, @Param("example") TblInstMerKeyInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_KEY_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblInstMerKeyInfoDO record, @Param("example") TblInstMerKeyInfoDOExample example);
}