package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblInstRouteControl;
import com.allcheer.bpos.entity.TblInstRouteControlExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblInstRouteControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_ROUTE_CONTROL
     *
     * @mbggenerated
     */
    int countByExample(TblInstRouteControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_ROUTE_CONTROL
     *
     * @mbggenerated
     */
    int deleteByExample(TblInstRouteControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_ROUTE_CONTROL
     *
     * @mbggenerated
     */
    int insert(TblInstRouteControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_ROUTE_CONTROL
     *
     * @mbggenerated
     */
    int insertSelective(TblInstRouteControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_ROUTE_CONTROL
     *
     * @mbggenerated
     */
    List<TblInstRouteControl> selectByExample(TblInstRouteControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_ROUTE_CONTROL
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblInstRouteControl record, @Param("example") TblInstRouteControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_ROUTE_CONTROL
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblInstRouteControl record, @Param("example") TblInstRouteControlExample example);
}