package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblInstMerAddBatchInfoDO;
import com.allcheer.bpos.entity.TblInstMerAddBatchInfoDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblInstMerAddBatchInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int countByExample(TblInstMerAddBatchInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(TblInstMerAddBatchInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String batchNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int insert(TblInstMerAddBatchInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int insertSelective(TblInstMerAddBatchInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    List<TblInstMerAddBatchInfoDO> selectByExample(TblInstMerAddBatchInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    TblInstMerAddBatchInfoDO selectByPrimaryKey(String batchNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblInstMerAddBatchInfoDO record, @Param("example") TblInstMerAddBatchInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblInstMerAddBatchInfoDO record, @Param("example") TblInstMerAddBatchInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblInstMerAddBatchInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_INST_MER_ADD_BATCH_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblInstMerAddBatchInfoDO record);
}