package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblMerRouteConfCountDO;
import com.allcheer.bpos.entity.TblMerRouteConfCountDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblMerRouteConfCountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_ROUTE_CONF_COUNT
     *
     * @mbggenerated
     */
    int countByExample(TblMerRouteConfCountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_ROUTE_CONF_COUNT
     *
     * @mbggenerated
     */
    int deleteByExample(TblMerRouteConfCountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_ROUTE_CONF_COUNT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_ROUTE_CONF_COUNT
     *
     * @mbggenerated
     */
    int insert(TblMerRouteConfCountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_ROUTE_CONF_COUNT
     *
     * @mbggenerated
     */
    int insertSelective(TblMerRouteConfCountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_ROUTE_CONF_COUNT
     *
     * @mbggenerated
     */
    List<TblMerRouteConfCountDO> selectByExample(TblMerRouteConfCountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_ROUTE_CONF_COUNT
     *
     * @mbggenerated
     */
    TblMerRouteConfCountDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_ROUTE_CONF_COUNT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblMerRouteConfCountDO record, @Param("example") TblMerRouteConfCountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_ROUTE_CONF_COUNT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblMerRouteConfCountDO record, @Param("example") TblMerRouteConfCountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_ROUTE_CONF_COUNT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblMerRouteConfCountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_ROUTE_CONF_COUNT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblMerRouteConfCountDO record);
}