package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblMerChannelPreInfoDO;
import com.allcheer.bpos.entity.TblMerChannelPreInfoDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblMerChannelPreInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CHANNEL_PRE_INFO
     *
     * @mbggenerated
     */
    int countByExample(TblMerChannelPreInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CHANNEL_PRE_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(TblMerChannelPreInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CHANNEL_PRE_INFO
     *
     * @mbggenerated
     */
    int insert(TblMerChannelPreInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CHANNEL_PRE_INFO
     *
     * @mbggenerated
     */
    int insertSelective(TblMerChannelPreInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CHANNEL_PRE_INFO
     *
     * @mbggenerated
     */
    List<TblMerChannelPreInfoDO> selectByExample(TblMerChannelPreInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CHANNEL_PRE_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblMerChannelPreInfoDO record, @Param("example") TblMerChannelPreInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CHANNEL_PRE_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblMerChannelPreInfoDO record, @Param("example") TblMerChannelPreInfoDOExample example);

    int countByCust(@Param("instId") String instId, @Param("merId") String merId, @Param("instMerId") String instMerId,@Param("channelMerId") String channelMerId,@Param("channelStat") String channelStat);

    public List<TblMerChannelPreInfoDO> selectByCust(@Param("instId") String instId, @Param("merId") String merId,
                                                     @Param("instMerId") String instMerId,@Param("channelMerId") String channelMerId,@Param("channelStat") String channelStat);
}