package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblMerBankInfoDO;
import com.allcheer.bpos.entity.TblMerInfoDO;
import com.allcheer.bpos.entity.TblMerInfoDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblMerInfoDOMapper {


    List<TblMerInfoDO> selectMerId ();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    int countByExample(TblMerInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(TblMerInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String merId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    int insert(TblMerInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    int insertSelective(TblMerInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    List<TblMerInfoDO> selectByExample(TblMerInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    TblMerInfoDO selectByPrimaryKey(String merId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblMerInfoDO record, @Param("example") TblMerInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblMerInfoDO record, @Param("example") TblMerInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblMerInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblMerInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    int selectIfMerInfo(@Param("record") TblMerInfoDO record, @Param("record2") TblMerBankInfoDO record2);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    int selectMerByPhoneNumber(@Param("record") TblMerInfoDO record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    int selectMerByCertNum(@Param("record") TblMerInfoDO record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_INFO
     *
     * @mbggenerated
     */
    int selectMerByBankAccountNo(@Param("record") TblMerBankInfoDO record);
    
}