package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblMerRelevanceMccDo;
import com.allcheer.bpos.entity.TblMerRelevanceMccDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblMerRelevanceMccDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    int countByExample(TblMerRelevanceMccDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    int deleteByExample(TblMerRelevanceMccDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    int insert(TblMerRelevanceMccDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    int insertSelective(TblMerRelevanceMccDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    List<TblMerRelevanceMccDo> selectByExample(TblMerRelevanceMccDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblMerRelevanceMccDo record, @Param("example") TblMerRelevanceMccDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_RELEVANCE_MCC
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblMerRelevanceMccDo record, @Param("example") TblMerRelevanceMccDoExample example);
}