package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.vo.TblMerAuditRecordVO;

import java.util.List;
import java.util.Map;

public interface TblMerAuditRecordVOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_AUDIT_RECORD
     *
     * @mbggenerated
     */
    int countByCondition(Map<String,String> condition);

    List<TblMerAuditRecordVO> selectByCondition(Map<String,String> condition);

}