package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblMerCoreMccDo;
import com.allcheer.bpos.entity.TblMerCoreMccDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblMerCoreMccDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CORE_MCC
     *
     * @mbggenerated
     */
    int countByExample(TblMerCoreMccDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CORE_MCC
     *
     * @mbggenerated
     */
    int deleteByExample(TblMerCoreMccDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CORE_MCC
     *
     * @mbggenerated
     */
    int insert(TblMerCoreMccDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CORE_MCC
     *
     * @mbggenerated
     */
    int insertSelective(TblMerCoreMccDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CORE_MCC
     *
     * @mbggenerated
     */
    List<TblMerCoreMccDo> selectByExample(TblMerCoreMccDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CORE_MCC
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblMerCoreMccDo record, @Param("example") TblMerCoreMccDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MER_CORE_MCC
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblMerCoreMccDo record, @Param("example") TblMerCoreMccDoExample example);
}