package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblOnlineUserLoginDO;
import com.allcheer.bpos.entity.TblOnlineUserLoginDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblOnlineUserLoginDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ONLINE_USER_LOGIN
     *
     * @mbggenerated
     */
    int countByExample(TblOnlineUserLoginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ONLINE_USER_LOGIN
     *
     * @mbggenerated
     */
    int deleteByExample(TblOnlineUserLoginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ONLINE_USER_LOGIN
     *
     * @mbggenerated
     */
    int insert(TblOnlineUserLoginDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ONLINE_USER_LOGIN
     *
     * @mbggenerated
     */
    int insertSelective(TblOnlineUserLoginDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ONLINE_USER_LOGIN
     *
     * @mbggenerated
     */
    List<TblOnlineUserLoginDO> selectByExample(TblOnlineUserLoginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ONLINE_USER_LOGIN
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblOnlineUserLoginDO record, @Param("example") TblOnlineUserLoginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ONLINE_USER_LOGIN
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblOnlineUserLoginDO record, @Param("example") TblOnlineUserLoginDOExample example);
}