package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TBLOutcomeBankRecordDO;
import com.allcheer.bpos.entity.TBLOutcomeBankRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBLOutcomeBankRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_BANK_RECORD
     *
     * @mbggenerated
     */
    int countByExample(TBLOutcomeBankRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_BANK_RECORD
     *
     * @mbggenerated
     */
    int deleteByExample(TBLOutcomeBankRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_BANK_RECORD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_BANK_RECORD
     *
     * @mbggenerated
     */
    int insert(TBLOutcomeBankRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_BANK_RECORD
     *
     * @mbggenerated
     */
    int insertSelective(TBLOutcomeBankRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_BANK_RECORD
     *
     * @mbggenerated
     */
    List<TBLOutcomeBankRecordDO> selectByExample(TBLOutcomeBankRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_BANK_RECORD
     *
     * @mbggenerated
     */
    TBLOutcomeBankRecordDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_BANK_RECORD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TBLOutcomeBankRecordDO record, @Param("example") TBLOutcomeBankRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_BANK_RECORD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TBLOutcomeBankRecordDO record, @Param("example") TBLOutcomeBankRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_BANK_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TBLOutcomeBankRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_BANK_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TBLOutcomeBankRecordDO record);
}