package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblOutcomeRecordBatch;
import com.allcheer.bpos.entity.TblOutcomeRecordBatchExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblOutcomeRecordBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_RECORD_BATCH
     *
     * @mbggenerated
     */
    int countByExample(TblOutcomeRecordBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_RECORD_BATCH
     *
     * @mbggenerated
     */
    int deleteByExample(TblOutcomeRecordBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_RECORD_BATCH
     *
     * @mbggenerated
     */
    int insert(TblOutcomeRecordBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_RECORD_BATCH
     *
     * @mbggenerated
     */
    int insertSelective(TblOutcomeRecordBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_RECORD_BATCH
     *
     * @mbggenerated
     */
    List<TblOutcomeRecordBatch> selectByExample(TblOutcomeRecordBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_RECORD_BATCH
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblOutcomeRecordBatch record, @Param("example") TblOutcomeRecordBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_OUTCOME_RECORD_BATCH
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblOutcomeRecordBatch record, @Param("example") TblOutcomeRecordBatchExample example);
}