package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblProvDO;
import com.allcheer.bpos.entity.TblProvDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblProvDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_PROVINCE
     *
     * @mbggenerated
     */
    int countByExample(TblProvDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_PROVINCE
     *
     * @mbggenerated
     */
    int deleteByExample(TblProvDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_PROVINCE
     *
     * @mbggenerated
     */
    int insert(TblProvDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_PROVINCE
     *
     * @mbggenerated
     */
    int insertSelective(TblProvDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_PROVINCE
     *
     * @mbggenerated
     */
    List<TblProvDO> selectByExample(TblProvDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_PROVINCE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblProvDO record, @Param("example") TblProvDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_PROVINCE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblProvDO record, @Param("example") TblProvDOExample example);
}