package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblT1CheckFileRespondeDo;
import com.allcheer.bpos.entity.TblT1CheckFileRespondeDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblT1CheckFileRespondeDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T1_CHECK_FILE_RESPONDE
     *
     * @mbggenerated
     */
    int countByExample(TblT1CheckFileRespondeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T1_CHECK_FILE_RESPONDE
     *
     * @mbggenerated
     */
    int deleteByExample(TblT1CheckFileRespondeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T1_CHECK_FILE_RESPONDE
     *
     * @mbggenerated
     */
    int insert(TblT1CheckFileRespondeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T1_CHECK_FILE_RESPONDE
     *
     * @mbggenerated
     */
    int insertSelective(TblT1CheckFileRespondeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T1_CHECK_FILE_RESPONDE
     *
     * @mbggenerated
     */
    List<TblT1CheckFileRespondeDo> selectByExample(TblT1CheckFileRespondeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T1_CHECK_FILE_RESPONDE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblT1CheckFileRespondeDo record, @Param("example") TblT1CheckFileRespondeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T1_CHECK_FILE_RESPONDE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblT1CheckFileRespondeDo record, @Param("example") TblT1CheckFileRespondeDoExample example);
}