package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblT0CheckFileResponseDo;
import com.allcheer.bpos.entity.TblT0CheckFileResponseDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblT0CheckFileResponseDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T0_CHECK_FILE_RESPONSE
     *
     * @mbggenerated
     */
    int countByExample(TblT0CheckFileResponseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T0_CHECK_FILE_RESPONSE
     *
     * @mbggenerated
     */
    int deleteByExample(TblT0CheckFileResponseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T0_CHECK_FILE_RESPONSE
     *
     * @mbggenerated
     */
    int insert(TblT0CheckFileResponseDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T0_CHECK_FILE_RESPONSE
     *
     * @mbggenerated
     */
    int insertSelective(TblT0CheckFileResponseDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T0_CHECK_FILE_RESPONSE
     *
     * @mbggenerated
     */
    List<TblT0CheckFileResponseDo> selectByExample(TblT0CheckFileResponseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T0_CHECK_FILE_RESPONSE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblT0CheckFileResponseDo record, @Param("example") TblT0CheckFileResponseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_T0_CHECK_FILE_RESPONSE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblT0CheckFileResponseDo record, @Param("example") TblT0CheckFileResponseDoExample example);
}