package com.allcheer.bpos.mapper;

import com.allcheer.bpos.entity.TblWechatIncomeCheckFileDo;
import com.allcheer.bpos.entity.TblWechatIncomeCheckFileDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblWechatIncomeCheckFileDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WECHAT_INCOME_CHECK_FILE
     *
     * @mbggenerated
     */
    int countByExample(TblWechatIncomeCheckFileDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WECHAT_INCOME_CHECK_FILE
     *
     * @mbggenerated
     */
    int deleteByExample(TblWechatIncomeCheckFileDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WECHAT_INCOME_CHECK_FILE
     *
     * @mbggenerated
     */
    int insert(TblWechatIncomeCheckFileDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WECHAT_INCOME_CHECK_FILE
     *
     * @mbggenerated
     */
    int insertSelective(TblWechatIncomeCheckFileDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WECHAT_INCOME_CHECK_FILE
     *
     * @mbggenerated
     */
    List<TblWechatIncomeCheckFileDo> selectByExample(TblWechatIncomeCheckFileDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WECHAT_INCOME_CHECK_FILE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblWechatIncomeCheckFileDo record, @Param("example") TblWechatIncomeCheckFileDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WECHAT_INCOME_CHECK_FILE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblWechatIncomeCheckFileDo record, @Param("example") TblWechatIncomeCheckFileDoExample example);
}